steemit/condenser

app/components/cards/PostFull.jsx
app/components/elements/TagList.jsx
app/components/elements/TagList.scss

Removed full article tags from the header section. Tags still present
in the footer.
Switched from a dropdown to a list of individual tags in pill format.

Tag list updates

---

README.md
app/assets/stylesheets/forms.scss
app/components/pages/Witnesses.jsx

Ability to enter a witness username manually

---

app/ResolveRoute.js
app/components/cards/UserListRow.jsx
app/components/elements/UserList.jsx
app/components/pages/UserProfile.jsx
app/components/pages/UserProfile.scss

Links to the pages are in the user header. Should complete the bare
minimum requirements for steemit/steemit.com#112.

Added Following/Followed pages

---

README.md
config/steem-example.json

Includes using @TigerND brew for steemd, addresses #135

Updates to README fleshing out OS X instructions

---

circle.yml
package.json

235 circleci

---

app/redux/FetchDataSaga.test.js
package.json
server/server.test.js

Passes now! 😃 
thanks to @jcalfee :D

Reenable some mocha tests

---

npm-shrinkwrap.json
server/server-html.jsx
webpack/base.config.js
webpack/dev.config.js
webpack/prod.config.js

Make webpack to use ExtractTextPlugin in dev env too (close #257)

---

app/components/elements/Voting.jsx

Minor fixes to the Flag dialog.

Flag dialog: fix button style & spelling

---

app/components/cards/CategorySelector.jsx

The node is truncating at 32 characters, and we may need to tighten it up further. Setting max to 24 for now...

add max tag length check

---

app/assets/icons/reblog.svg
app/components/all.scss
app/components/cards/PostFull.jsx
app/components/cards/PostFull.scss
app/components/cards/PostSummary.jsx
app/components/cards/PostSummary.scss
app/components/cards/PostsList.jsx
app/components/elements/Icon.jsx
app/components/elements/Reblog.jsx
app/components/elements/Reblog.scss
app/components/pages/UserProfile.jsx
app/redux/FetchDataSaga.js
app/redux/GlobalReducer.js

Working well, waiting for backend.
This should not be merged until https://github.com/steemit/steem/issues/401 is resolved and merged into develop.

Reblogging functionality #203

---

app/components/cards/Comment.jsx
app/components/cards/Comment.scss
app/components/pages/Post.jsx

Fixes scroll-to functionality and adds comment highlighting.

Fix comment anchor, resolves #227

---

app/components/cards/PostFull.jsx
app/components/cards/PostSummary.jsx
app/components/elements/Reblog.jsx

- Performance
- Rename to "Resteem"
- Hide for own posts
- Hide for archived posts

Reblog updates #203

---

app/components/pages/UserProfile.jsx
app/redux/FetchDataSaga.js
app/redux/GlobalReducer.js

Do not merge until https://github.com/steemit/steem/issues/445 is resolved

Profile pagination: comments & replies, resolves #232

---

app/components/pages/UserProfile.jsx
app/redux/FetchDataSaga.js
app/redux/GlobalReducer.js

Reverts steemit/steemit.com#288

Revert "Profile pagination: comments & replies, resolves #232"

---

app/components/elements/ReplyEditor.scss

The toolbar should no longer disappear off the top of the screen.
Needs testing on mobile!

make rte editor body scrollable. #82

---

app/components/modules/Header.jsx

* User's Followers page (People following)
* User's Followed page (People followed by)
* User's Comments Tab (Comments by)
* User's Replies Tab (Replies by)
* User's Author Rewards Tab (Author rewards by)
* User's Curation Rewards Tab (Curation rewards by)

SEO Page Title Improvements #314

---

app/redux/GlobalReducer.js

Fix blog pagination when last item is a reblog - resolves #313

---

app/components/modules/Header.jsx

- Created (New topic posts)
- Trending (Trending topic posts)
- Hot (Hot topic posts)
- Promoted (Promoted topic posts)
- Active (Active topic posts)

SEO (Improve readability of post category titles) #327

---

app/components/modules/Header.jsx

Similar to https://steemit.com/steemit-bug/@ash/steemit-bug-fix-feed-ttitle

Fix various page titles

---

app/components/cards/TransferHistoryRow.jsx
app/components/elements/Memo.js
app/components/elements/SavingsWithdrawHistory.jsx
app/components/elements/Template.jsx
app/components/modules/Transfer.jsx
app/components/modules/UserWallet.jsx
app/components/modules/UserWallet.scss
app/redux/User.js
app/redux/UserSaga.js
app/utils/ReactForm.js
app/utils/Tips.js
shared/serializer/src/ChainTypes.js
shared/serializer/src/operations.js

Demo: https://youtu.be/iex-ZlIl0rg

223 transfer to savings

---

app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js
app/locales/jp.js
app/locales/ru.js

This was on the front page and what new users will see:

Fix $ Signs in Locale Strings

---

app/components/modules/LoginForm.jsx
app/utils/ReactForm.js

Fixes save login checkbox to remember last status.

---

app/components/elements/DropdownMenu.jsx
app/components/elements/Voting.jsx

DropdownMenu.jsx
- Do not show dropdown menu if there are 0 items for the verticalmenu
Voting.jsx
- Only show 'Potential Payout' if > 0
- Only show 'Promotion Cost' if > 0
- Only show voters dropdown if there are votes
- Do not show "0 votes"
- Rename 'Max Payout' to 'Max Accepted Payout'
---
**Archived post before/after**
**zero-votes comment before/after**

Tidy dropdowns

---

app/components/elements/FoundationDropdownMenu.jsx
app/components/modules/UserWallet.jsx
app/components/modules/UserWallet.scss

Update for bug in foundation causing malformed wallet balance drop downs on mobile/collapsed views.

528 wallet balance alignment

---

app/components/elements/ShowKey.js
app/components/modules/UserWallet.jsx

**Currently, users on mobile will see:**
***
**With these changes:**

Fix various UI glitches on mobile

---

app/ResolveRoute.js
app/RootRoute.js
app/components/App.jsx
app/components/cards/MarkdownViewer.jsx
app/components/elements/HelpContent.jsx
app/components/modules/LoginForm.jsx
app/components/pages/Login.jsx
app/components/pages/PostsIndex.jsx
app/components/pages/UserProfile.jsx
app/components/pages/Welcome.jsx
app/help/en/welcome.md
app/redux/UserSaga.js

For issue #404
Added welcome page that new users redirect to.
A link has been added in the hamburger and in an empty blog.
Related post: https://steemit.com/help/@timcliff/the-official-welcome-to-steemit-landing-page-has-been-submitted-to-github-as-a-pull-request

Add welcome page and link in hamburger and empty blog

---

app/utils/ParsersAndFormatters.js

offset for rep float bug, resolves #643

---

app/assets/stylesheets/app.scss
app/components/elements/FormattedAsset.jsx
app/components/elements/Voting.jsx

Add html strikethrough on payout amount for posts that declined payout.

---

app/locales/en.js

fix reply count var and singlular counts

---

app/components/cards/CategorySelector.jsx
app/components/pages/TagsIndex.jsx
app/components/pages/Topics.jsx
app/redux/tests/global.json

tested against v0.16.0rc1, needs testing against live nodes

support for new tags and tag_idx state, close #689

---

app/components/pages/UserProfile.jsx
server/server.js

Allows viewing profile pages regardless if account name is entered malformed in URL(with any capitalized letters)

663 handle malformed manual usernames

---

app/components/cards/Comment.scss
app/components/elements/Userpic.jsx
app/components/elements/Userpic.scss
app/components/modules/Header.scss
app/components/modules/TopRightMenu.jsx
app/components/modules/TopRightMenu.scss

to allow for client-side square crop (current method stretches images which are not square)

css based userpic

---

release-notes.txt

release notes are current as of https://github.com/steemit/steemit.com/commit/92fe3673599963b764377831729f8e3d31cb65d7
`develop` needs more testing against 0.15.0 and 0.16.0

release notes - 0.1.161123

---

app/components/elements/DropdownMenu.jsx

dropdown onclick event should be ignored

---

app/components/modules/Header.jsx
app/components/pages/PostsIndex.jsx
app/components/pages/UserProfile.scss
app/locales/en.js

- hide promoted tab
- Fix "No #undefined posts found" msg
- Fix user banner Userpic alignment
- "value posts" -> "low value posts"

styling and copy fixes

---

app/components/cards/Comment.scss

and decrease last paragraph's bottom margin instead. fixes #677

remove negative top margin on comment footer

---

app/components/all.scss
app/components/cards/PostFull.jsx
app/components/elements/ShareMenu.jsx
app/components/elements/ShareMenu.scss

This fixes bug https://github.com/steemit/steemit.com/issues/410 - This removes the dropdown and brings the sharing directly on the post view.

411 cant scroll share

---

server/server.js

Handle cased category filtering

Handle for malformed case on top categories

---

app/components/cards/PostFull.jsx
app/components/cards/PostFull.scss
app/components/elements/PageViewsCounter.jsx
app/components/elements/ShareMenu.jsx
app/components/elements/ShareMenu.scss
app/components/elements/YoutubePreview.jsx
server/api/general.js

- add power up icon to PostFull
- add hover effect for new share icons
- use higher res for youtube preview image

Release fixes

---

app/components/pages/UserProfile.jsx
app/components/pages/UserProfile.scss

This fixes follow/mute actions when collapsed(mobile view). No longer do they overlap the username & rep score.

746 follow mute should

---

app/components/pages/UserProfile.jsx
app/utils/NormalizeProfile.js

Adds 'http://' to urls in the case it's missing, and opens the links in a new tab.

783 meta links

---

app/components/elements/Author.scss
app/components/modules/Settings.jsx
app/utils/NormalizeProfile.js

and minor adjust author dropdown alignment (make sure bio always starts on a new line)

enforce display names not starting with @

---

app/components/cards/CategorySelector.jsx
app/components/cards/PostFull.jsx
app/components/elements/Voting.jsx
app/components/modules/Header.jsx
app/components/pages/TagsIndex.jsx
app/components/pages/TagsIndex.scss
app/components/pages/Topics.jsx
app/components/pages/UserProfile.jsx
app/redux/FollowSaga.js
app/redux/GlobalReducer.js

- removes 0.15.0 compatibility
- restore Promote button and promoted posts listing
- update TagsIndex

remove 0.15.0 compat layer

---

app/ResolveRoute.js
app/RootRoute.js
app/components/cards/TransferHistoryRow.jsx
app/components/modules/Header.jsx
app/components/pages/PostPageNoCategory.jsx
app/redux/FetchDataSaga.js
app/redux/SagaShared.js
app/redux/TransactionSaga.js
app/utils/ExtractMeta.js
shared/UniversalRender.jsx

This PR adds a redirect component that looks up the post data using `get_content` and then redirects to /category/@user/permlink. If the call goes to the server `get_content` is used there also which makes the redirect happen quicker on the client side.
Since we can now link to /@author/permlink this PR also includes a fix for the curation reward links.

608 @author/permlink redirect

---

app/components/elements/Reblog.jsx
app/components/modules/ConfirmTransactionForm.jsx
app/components/modules/PromotePost.jsx
app/locales/en.js
app/locales/ru.js

Gracefully handle off screen click on confirmation

765 resteem issue

---

app/components/cards/PostsList.scss

Potential FF bug protection for scrolling.

Add overlay scroll for potential firefox bug not able to scroll a post

---

app/components/pages/Post.jsx
app/locales/en.js

currently it reads `If you enjoyed what you read here, earn 9 Steem Power [...]`
it will now read `If you enjoyed what you read here, earn $9 of Steem Power [...]`

fix post footer promo text

---

app/components/modules/BlocktradesDeposit.jsx

translation of blocktrades deposit

---

CONTRIBUTORS.md

added an initial draft/template for `CONTRIBUTORS.md` using [this one](https://github.com/google/protobuf/blob/master/CONTRIBUTORS.txt) as a reference

add contributors.md

---

app/components/cards/PostsList.scss

Bug introduced in https://github.com/steemit/steemit.com/commit/27c3bf12c9338139166df13c2043bc7ca63fedd1
@svk31 could you please review and make sure your fixes still work?

allow votes dropdown to expand past post modal #762

---

server/server_pages/enter_confirm_mobile.jsx

phone is considered to be used only if there is account created with it

---

app/redux/FetchDataSaga.js

Old logic: do not refetch page when the path is the same as server_location
This creates inconsistent UX:
- If you load your feed page from the server, you can never "refresh" it by clicking it in the menu
- If you load your blog page but then go to your feed, you *can* refresh your feed via menu
As far as I can tell, this logic is only supposed to prevent immediate refetching on initial load, so I've corrected it. Link/navigation behavior is now much more consistent.
Ref: #593, #516

allow refetching of pages #593

---

app/utils/StateFunctions.js

ensure tag is not null before attempting to match

fix account page 500 error #894

---

app/components/cards/Comment.jsx
app/components/pages/Post.jsx
app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js
app/locales/jp.js
app/locales/ru.js

changes:
- "trending" sorts by total payout
- "votes" counts only upvotes
- "new" sort renamed to "age"

enhance comment sorts 876

---

app/help/en/welcome.md

- Updated a lot of wording as per suggestions from @sneak and @pfunks
- Standardized capitalization using the rules from @sneak and @pfunks
- Clarified where to find the "Helpful Posts from Steemit Users" section
- Added info on where to find the 'Welcome Page' in the menu
- Added info on the new decline payout option
- Added info for the new sections in the user profile menu: Feed, Change Password, Settings, and Logout
- Removed language to "check replies frequently" since notifications have now been added
- Clarified instructions for users to backup and secure their password
- Added instructions to setup user profile and avatar
- Added instructions to set "NSFW" display setting
- Added new content to the "Helpful Posts from Steemit Users" section
- Added a link to Steemit Help …

Welcome Page Copyedit Changes for #723

---

app/utils/ExtractContent.js

Fix for ticket: https://github.com/steemit/steemit.com/issues/928

#928 Parse block quote from text if preview text is rendered as comment

---

app/assets/stylesheets/app.scss
app/components/pages/NotFound.jsx
app/redux/FetchDataSaga.js
server/server-error.jsx
shared/UniversalRender.jsx

This PR addresses a few tickets.  
https://github.com/steemit/steemit.com/issues/844
https://github.com/steemit/steemit.com/issues/693
https://github.com/steemit/steemit.com/issues/425
1.  Not found accounts now render our standard 404 page. (example: http://steemit.com/@nothinghere
2.  404 page has been completed revamped(screenshot attached).  
-   Improved navigation.
-   Improved UI (Match feel of our site).
-   Improved verbiage more friendly for end users.

844 routes user

---

app/components/elements/ReplyEditor.jsx
app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js
app/locales/jp.js
app/locales/normalize.sh
app/locales/ru.js
app/utils/ExtractContent.js

comment edit bug 895

---

config/client_config.js

Was causing bugs on pages which rely on VESTS and assetFloat method

restore a const which was removed in #846

---

app/components/elements/ReplyEditor.jsx
app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js

Reverts steemit/steemit.com#951
5 tags are working again.

Revert "Reduce tag limit #918"

---

app/components/modules/UserWallet.jsx

- "Deposit" --> "Buy"
- "Buy or Sell" --> "Market"

clarify wording of wallet actions, fix #628

---

app/components/pages/TagsIndex.jsx
app/components/pages/Topics.jsx

Screen shots: https://github.com/steemit/steemit.com/issues/997

Remove tags filter until full search is available. fix #997

---

app/components/elements/ReplyEditor.jsx
shared/HtmlReady.js

- move categories logic lower to where it's used, and lightly simplify
- add todo notes to HtmlReady

clean up replyeditor tag logic

---

app/components/cards/Comment.jsx
app/components/cards/PostFull.jsx
app/components/cards/PostFull.scss

show author's userpic below the title on post page (close #1050)

---

app/ResolveRoute.js
app/components/cards/Comment.jsx
app/components/cards/PostFull.jsx
app/components/cards/PostSummary.jsx
app/components/cards/PostsList.jsx
app/components/elements/VotesAndComments.jsx
app/components/elements/Voting.jsx
app/redux/RootReducer.js
app/utils/StateFunctions.js
shared/UniversalRender.jsx

~TODO: restore ignoring rshares from neg-rep votes~

1040 smaller server response

---

app/components/elements/FoundationDropdown.jsx
app/components/elements/Voting.jsx
app/components/elements/Voting.scss

when closed by clicking outside the slider

fix upvote slider positioning on mobile; fix slider's inconsistent state

---

app/redux/FollowSaga.js

https://github.com/steemit/steemit.com/issues/1002

1002 fetch followers 100

---

app/components/cards/PostFull.jsx
app/components/cards/PostFull.scss
app/components/elements/TimeAgoWrapper.js
app/components/elements/Tooltip.jsx
app/components/elements/Voting.scss

Adjust author heading

---

app/components/cards/Comment.jsx
app/components/cards/Comment.scss
app/components/cards/PostsList.jsx
app/components/pages/Post.jsx
app/utils/StateFunctions.js

- do not gray posts when they have positive payout
- move post-hiding logic into Comment.jsx and make it recursive

adjust graying and post collapsing rules

---

app/ResolveRoute.js
server/json/user_json.jsx

1118 update json profile

---

app/components/elements/ReplyEditor.scss
shared/HtmlReady.js

and add small vertical padding for markdown preview pane

fix HtmlReady regression -- domparser needs a root node

---

config/custom-environment-variables.json

Added SDC_UPLOAD_IMAGE_URL and SDC_SESSION_COOKIE_KEY to custom environment variables

Sneak updateconfig

---

server/teleSign.js

Removed braces around customer_id definition

critical telesign bugfix

---

app/components/elements/PageViewsCounter.jsx

#1178 Add commas to the view count

---

app/assets/stylesheets/app.scss
app/help/en/faq.md

@pfunks and I are are working on changes to the FAQ page to add a lot of additional content. As part of the changes, we will be adding a table of contents. The purpose of this PR is to get feedback on the TOC part of the change, so that we can determine the correct conventions/format/structure/style to follow for the larger FAQ.
The TOC will be at the top of the page, and will have links to each question:
The questions will be organized into categories, but for the purpose of this PR I just used fake/sample categories. This is so I didn't have to move the questions around, which would have introduced a bunch of unnecessary differences to the file. (In the final version, we will decide on actual categories and move the questions around to be in the right ones.)
Clinking on a link brings …

(WIP) Adding Table of Contents to FAQ Page - Feedback Requested

---

app/components/cards/TransferHistoryRow.jsx

this works with steemd/master. not 0.16.3.

show fill_convert_request and fill_order ops in wallet

---

app/ResolveRoute.js
app/components/modules/Header.jsx
app/redux/FetchDataSaga.js

this will be implemented with HF17 release
needs testing as posts + comments will be shown alongside

add payout sort [HF17]

---

app/components/modules/UserWallet.jsx
app/components/modules/UserWallet.scss
app/redux/AuthSaga.js
shared/serializer/src/ChainTypes.js
shared/serializer/src/operations.js

WIP. 
Still getting the following error: `TransactionSage Error: transaction.operations = claim_reward_balance,[object Object]	 cause: Cannot read property 'operation_name' of undefined`.
Please review changes, especially to `shared/serializer/src/operations.js`!

claim rewards feature

---

server/server_pages/enter_confirm_mobile.jsx

"VOIP services like Google Voice are not supported"
https://github.com/steemit/condenser/issues/1214

Added note about VOIP as per issue 1214

---

app/components/cards/Comment.jsx
app/redux/GlobalReducer.js

1) ensure `children` key is kept in sync in reducer
2) increase visible comment depth by 1

fix disappearing comments bug

---

app/help/en/welcome.md

- Updated the "Payouts" section for info on 7 day payouts (instead of 24h/30d)
- Removed @dantheman from people to follow
- Clarified live help
- Updated posts in the "Helpful Posts from Steemit Users" section

Welcome Page Updates

---

app/redux/FetchDataSaga.js

may want to bundle this with steem-js version bump when https://github.com/steemit/steem-js/pull/127/files is merged

update api calls for new format

---

app/components/App.jsx
app/components/elements/GeneratedPasswordInput.jsx
app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js
app/locales/jp.js

Commits should be self-explanatory. The partly server-side signup flow bypasses the router (and the App.jsx checks I added) which is why I added the delayed password generation in <GeneratedPasswordInput />

Only enable entropy collection when actually required

---

package.json
yarn.lock

https://github.com/steemit/steem-js/releases/tag/v0.5.5
updates crypto and fixes `payout` page paginations

upgrade steemjs to 0.5.5

---

app/components/modules/UserWallet.jsx

"claim" is a bad verb and implies that something happens to them if they're unclaimed.

change wording on reward claiming alert box

---

app/assets/static/search.html
app/components/modules/TopRightMenu.jsx
app/components/pages/PostsIndex.jsx
app/locales/en.js
app/locales/es.js
app/locales/es_AR.js
app/locales/fr.js
app/locales/it.js
app/locales/jp.js
app/locales/ru.js

The main fixes are the vertical displacement of the header happening when the LoadingIndicator is active, and making the search page header look similar to the regular header. I've also made it so search results open inside the same window.
I've included a minor update to PostsIndex that I spotted while working on this since it doesn't really need its own branch anyway, just adds some translations and makes some links internal so they don't refresh the whole page for no reason.

Header fixes

---

app/utils/BadActorList.js

recently created account,
its variation,
dictionary suggestion from chromium browser

updated list of potential bad actors:

---

db/migrations/20170518201152-create-attributes.js
db/models/user.js
db/models/user_attributes.js
server/server.js
server/sign_up_pages/enter_confirm_email.jsx

A few new requested features:
1. User attribute table 
2. Store incoming referrer when user is created

Tracking landing page

---

app/redux/UserSaga.js

Caught some bad english, thought I would fix for you

Fixed Bad english

---

app/utils/BadActorList.js

removing livecoin.net from potential bad actors list

update to potential bad actors list

---

app/utils/SanitizeConfig.js

Trivial modification to accept tag i (though em should be preferred), as it is already for b (though strong should be preferred)

b and strong accepted both; em accepted but not i; accept i too

---

app/help/en/welcome.md

- Changes "Welcome Page" to "Quick Start Guide" in text.
- Removes outdated "Helpful Posts from Steemit Users".
- Rearranges order of "Helpful Posts from Steemit Users".
- Adds new "Helpful Posts from Steemit Users".
- Moves the 'FAQ' to the top of the "Other Resources" section.

Quick Start Guide Updates

---

app/help/en/faq.md

- Adds more info on the account creation process
- Adds new question:  How long does the account approval process take?
- Adds new question:  Am I allowed to create more than one account?
- Adds new question:  Why is the "Post" button grayed out?
- Adds new question:  What is delegated STEEM Power?
- Adds new question:  How long does it take STEEM or STEEM Power that I purchased to show up in my account?
- Adds new question:  What are curation trails?
- Updated info on using AnonSteem to create new blockchain accounts
- Added info for using SteemConnect to create new blockchain accounts
The content changes should be reviewed by @sneak before approving. Let me know if any changes are needed, and I will make the necessary updates.

Update FAQ Content

---

app/utils/BadActorList.js

https://steemit.com/steem/@steemitpatina/well-guess-i-m-a-dope-poliniex-and-poloniex-are-not-the-same-steem-lost-forever

Add new account to bad actor list

---

app/utils/BadActorList.js

https://steemit.com/steemit/@randowhale/do-not-submit-steem-sbd-to-randomwhale-it-s-randowhale-no-m

Add account to the bad actor list

---

app/help/en/faq.md

This pull request updates the FAQ to be consistent with the changes in HF 19 and also adds/updates some questions.
Updated questions:
- Will the reward pool pay out more or less depending on who votes?
- How do I get more STEEM Power
- What do the dollar amounts for pending payouts represent?
- How do Steem Dollar to STEEM conversions work
- Is there a way for me to convert my Steem Dollars to STEEM without waiting 3.5 days?
- How can I withdraw my STEEM or SBD coins
- What is my voting power?
- How many times can I vote without depleting my voting power?
- What is @cheetah?
- How can I extract these keys from my master password (question removed - too confusing for new users)

Faq updates hf19

---

app/components/elements/ReplyEditor.jsx

I just went ahead and made the very small change to this as I feel it's a pressing matter, and it's such a small change!

Default root post auto self vote to false (#1540)

---

app/utils/DMCAList.js

DMCA Takedown Notice received

---

README.md

Nothing major, but there are the things I thought needed updating in the README.md

Updated to README.md I found while setting up

---

app/components/all.scss
app/components/elements/Author.jsx
app/components/elements/Author.scss
app/components/elements/AuthorDropdown.jsx
app/components/elements/AuthorDropdown.scss
app/components/elements/Icon.scss
package.json

fix, author dropdown positioning, refs steemit/condenser #1533

---

app/utils/BadActorList.js

In reference to this user post:
https://steemit.com/steemet/@borishaifa/what-to-do-guys-i-have-made-a-mistake-with-steem

Add blocktades to badactor list

---

src/app/locales/en.json

Fixes 'view the direct parent' missing translation

---

README.md

Condenser's documentation has become heavily updated. This should bring it up-to-date.

Update condenser README

---

src/app/components/pages/PickAccount.jsx

Simple fix for 'already have *an* account?'

Grammar fix for 'already have an account?'

---

src/app/components/modules/Settings.jsx
src/app/components/pages/UserProfile.jsx
src/app/components/pages/UserProfile.scss
src/app/locales/en.json
src/app/locales/es.json
src/app/utils/NormalizeProfile.js

add cover image support #1651

---

src/app/components/cards/Comment.jsx
src/app/components/cards/MarkdownViewer.jsx
src/app/components/cards/PostFull.jsx
src/app/components/cards/PostSummary.jsx
src/app/utils/ImageUserBlockList.js
src/shared/HtmlReady.js

Users on the blocklist will not have their images displayed inline in content, instead the images they post will just show up as unclickable url's

Image blacklist

---

package.json
src/app/Main.js
yarn.lock

added k0nami monitoring to enable network logging. depends on npm linked steem-js branch api-injected-logging-support

konami-code

---

src/app/utils/ProxifyUrl.js
src/app/utils/ProxifyUrl.test.js
src/shared/HtmlReady.js

https://github.com/steemit/condenser/issues/1417
Added the ability to pass 'true' to the proxy url function to retain image sizing.

1417 retain image proxy url sizing

---

src/app/components/modules/Powerdown.jsx
src/app/locales/en.json

Fixes a couple of issues with the power down slider

Powerdown slider fixes

---

src/app/components/modules/Powerdown.jsx

Fixes #1744 (please verify @Gandalf-the-Grey)

Fix bug where a completed powerdown shows as unfinished

---

src/app/redux/TransactionSaga.js

Fixes issue #1738 Mis-spelled error message when sending encrypted memo

fixed #1738

---

src/shared/UniversalRender.jsx

This is helpful for development.

Add redux devtools middleware

---

src/app/utils/BadActorList.js

account belong to known abuser

updated bad actor list

---

src/app/components/modules/LoginForm.jsx
src/app/components/modules/LoginForm.scss
src/app/locales/en.json

Signup button tweak

---

src/app/utils/BadActorList.js

users mistakenly have sent deposits to these accounts

add blocktradess, blocktrade to warn list

---

src/server/server.js

https://github.com/steemit/condenser/issues/1800
This addresses eliminating the server redirect portion of 1800. *1) server doesn't redirect on /,*

1800 eliminate redirect

---

src/server/server.js

Reverts steemit/condenser#1801

Revert "1800 eliminate redirect"

---

src/app/RootRoute.js
src/app/components/elements/ReplyEditor.jsx
src/app/components/pages/SubmitPost.jsx
src/app/utils/ServerApiClient.js

please note I've commented out overseer console errors - they are really annoying, let's reenable them when it's fully supported

fix rte editing issue

---

src/app/components/App.jsx

whatever code is in there is not even being executed! any need for this setState anymore?

remove unused implementation of componentWillReceiveProps

---

package.json
src/server/index.js
yarn.lock

In my tests this simple change shows 46% SRR performance boost

add transform-inline-environment-variables babel plugin

---

package.json
yarn.lock

Reverts steemit/condenser#1843

Revert "bump steem-js version to 72a36c8"

---

package.json
yarn.lock

https://github.com/steemit/steem-js/compare/ec4439c...72a36c8

bump steem-js version to 72a36c8

---

src/app/components/App.jsx

Let's whistle have a clean page for signup in its iframe

Add qs to hide header on signup

---

src/app/components/cards/Comment.jsx

#1920 
Updates from use of body.scrollTop.
New theme header is shorter updated the offset. (we should probably create a story for deriving that live)

1920 - scrollTop fix

---

src/app/components/cards/PostSummary.jsx
src/shared/UniversalRender.jsx

1917 - from post list articles launch in main view. 

---

src/app/utils/UserUtil.js

fixes #2015 
will clean up the rest of these today; this is a hot fix for a critical issue

do not assume code only runs in-browser

---

src/server/server.js

Remove redundant Strict-Transport-Security response header

---

src/app/Main.js
src/app/assets/stylesheets/app.scss
src/app/components/App.jsx
src/app/components/pages/Approval.jsx
src/app/components/pages/PickAccount.jsx
src/app/utils/Links.js
src/app/utils/Links.test.js
src/server/app_render.jsx
src/server/sign_up_pages/enter_confirm_email.jsx
src/server/sign_up_pages/enter_confirm_mobile.jsx
src/shared/UniversalRender.jsx
src/shared/constants.js

Closes #1989 
Remove navigation that takes users out of signup flow. Remove possibility of 'beta' appearing anywhere.
Of necessity, the UI is very sparse. @pkattera approved.

Whistle signup flow updates

---

src/app/assets/stylesheets/app.scss
src/app/components/cards/PostSummary.jsx
src/app/components/cards/PostsList.jsx

remove post modal & associated code

---

Dockerfile

Reverts steemit/condenser#1712

Revert "move npm commands to yarn in Dockerfile"

---

src/app/components/cards/PostFull.jsx

fixes #2074
only show reply box on initial render for logged-in user

only open comment box one time

---

src/app/components/cards/PostFull.jsx

see #1465 
the previously merged fixes are buggy and should be reverted -- this is my bad for not testing thorougly

revert buggy solution to reply auto-open

---

src/app/components/elements/ReplyEditor.jsx

see #2066 
bug fix for post reply editor image upload

hotfix: add missing import for userActions

---

package.json

closes #2100
i didn't commit the correct command.
see #2081

actually run prettier

---

src/app/Main.js
src/app/components/App.jsx
src/app/components/App.scss
src/app/components/all.scss
src/app/components/modules/Modals.jsx
src/app/components/modules/SignUp.jsx
src/app/components/modules/SignUp.scss
src/app/components/pages/Post.jsx
src/server/api/account_recovery.js
src/server/api/general.js
src/server/api/oauth.js
src/server/app_render.jsx
src/server/server.js
src/server/sign_up_pages/enter_confirm_email.jsx
src/server/sign_up_pages/enter_confirm_mobile.jsx
src/shared/UniversalRender.jsx

re-opens #1810 
This reverts commit 65fbd1a6684c87783890b05015b087a323216a80, reversing
changes made to 769bba0cc68ed0748772c3329249ca64f4d3685d.

Revert "Merge pull request #1810 from steemit/offchain-state"

---

src/app/utils/VerifiedExchangeList.js

I used Changelly recently and noticed that it didn't remind me to enter a memo :)

Add Changelly to verified exchange list

---

src/app/components/cards/PostFull.jsx

Correcting the Schema.org schema type

Fixing issue #2118: Correcting the Schema.org schema type

---

src/shared/HtmlReady.js
src/shared/HtmlReady.test.js

match more mentions

---

src/app/utils/BadActorList.js

Add 'bittreex' to bad actors

---

package.json
yarn.lock

Remove unused medium editor plugin

---

src/shared/HtmlReady.js
src/shared/HtmlReady.test.js

Issue: #2128
Reverts steemit/condenser#1953

Revert "match more mentions"

---

src/app/components/elements/ReplyEditor.jsx
src/app/components/modules/PromotePost.jsx

Supercedes: PR: https://github.com/steemit/condenser/pull/1982

Fix for promotion text field 1930 2

---

src/app/components/elements/HorizontalMenu.jsx
src/app/components/elements/HorizontalMenu.scss
src/app/components/modules/Header.jsx
src/app/components/modules/Header.scss
src/app/components/modules/TopRightMenu.jsx

Supersedes:  https://github.com/steemit/condenser/pull/1992
I have reviewed and tested locally - all is good.

Add search input to the header

---

src/app/components/pages/Market.jsx
src/app/components/pages/Market.scss
src/app/redux/MarketReducer.js
src/app/redux/MarketReducer.test.js
src/app/utils/MarketUtils.js

closes #1757 
will work on adding tests for helper fn & the reducer

add sorting to open orders table

---

src/app/components/elements/ConvertToSteem.jsx
src/app/components/modules/UserWallet.jsx

Closes #2143 - remove Convert to Steem menu item from SBD dropdown

---

src/app/utils/BadActorList.js

Closes #2002 #2148

---

src/app/redux/OffchainReducer.js
src/app/redux/OffchainReducer.test.js

add test for offchain reducer

---

CONTRIBUTING.md

Updated contrib #2187

---

src/app/components/elements/UserList.jsx

fixes #2191, revert changes to UserList, fixes #2191

---

config/custom-environment-variables.json
config/default.json
package.json
src/app/Main.js
src/server/index.js
yarn.lock

Closes #2070 
~~Blocked by https://github.com/steemit/steem-js/pull/291~~

Use appbase APIs

---

src/app/components/elements/ReplyEditor.jsx

closes #2210 
removes the comment payout options

Revert #1955

---

src/app/components/cards/MarkdownViewer.jsx

This reverts commit e3a3fa116959eb8c599e655d070f88a88c032c08, reversing
changes made to a6ed14ff829bca191877a25794659087cb3dd14e.
this change might cause a mysterious performance issue

Revert "Merge pull request #2248 from steemit/2246-htmlready-lonely-frame"

---

src/app/redux/AppReducer.js
src/app/redux/AppReducer.test.js
src/app/redux/SagaShared.js

fixes #2185 
fixes #2294 
Issues described by @bnchdrff here
https://github.com/steemit/condenser/pull/2156#discussion_r157744256

add test for the AppReducer

---

src/app/redux/AppReducer.js
src/app/redux/AppReducer.test.js
src/app/redux/SagaShared.js

Fixes #2295 
This reverts commit c1e7fbb01f48e57b5cd64ac4e612ba0cf82bec25.

Revert "add test for the AppReducer (#2186)"

---

config/default.json

closes #2194
closes #2299
change default config to use https connection to steem api server

use https not wss

---

src/app/redux/AppReducer.js
src/app/redux/AppReducer.test.js
src/app/redux/SagaShared.js

closes #2185
closes #2294
This reverts commit f3312a7f0f6b4979ef9e20836e662d2a8d2aa9a5.

Revert "Revert "add test for the AppReducer (#2186)" (#2296)"

---

src/app/redux/TransactionSaga.test.js

i did a bad job of porting iain's mocha test workarounds for TransactionSaga's impure (timestamp-related) code; this is a better way of doing it.

deal with hard to test functions a bit more gracefully

---

src/app/utils/ReactForm.js

Add debounce for onChange validation #2282

---

package.json
yarn.lock

Closes #2374
[diff](https://github.com/steemit/steem-js/compare/74873bf70ec11f9765a6e4fb33faeb0b6ed23b49...a04fb9a2a6937354e5a485a8d9c88d07015cfc1d)

Update steem-js to 0.6.10 #2374

---

src/app/components/modules/TermsAgree.jsx
src/app/redux/AppReducer.test.js
src/app/redux/GlobalReducer.js
src/app/redux/GlobalReducer.test.js
src/app/redux/SagaShared.js
src/app/utils/JsPlugins.js
src/app/utils/StateFunctions.js

add test for GlobalReducer

---

package.json
src/app/components/modules/ConnectedFlag/README.md
src/app/components/modules/ConnectedFlag/index.jsx
src/app/components/modules/Flag/Flag.test.jsx
src/app/components/modules/Flag/index.jsx
src/app/redux/AppReducer.js
src/app/redux/AppReducer.test.js
src/app/redux/UserSaga.js
yarn.lock

closes #2179
rebase of #2305
rebase of im/2179/feature-flags
see src/app/components/modules/ConnectedFlag/README.md for docs
requests flags from conveyor at user login

add feature flags support

---

src/app/assets/stylesheets/foundation-overrides.scss
src/app/components/cards/PostSummary.jsx
src/app/components/pages/PostsIndex.scss

closes #2488
This reverts commit 14b6fea770fc0ebb835098c04fb6412b2e861c06.

Revert "add placeholder for loading images in blogmode, refs #2459"

---

src/app/ResolveRoute.js
src/app/ResolveRoute.test.js
src/app/components/cards/PostSummary.jsx
src/app/components/elements/SidebarNewUsers.jsx
src/app/components/elements/WelcomePanel.jsx
src/app/components/modules/LoginForm.jsx
src/app/components/modules/TopRightMenu.jsx
src/app/components/pages/Post.jsx
src/shared/constants.js

closes #2455 
hold off on merging this, obvs ;) ;)

link to new faucet

---

.storybook/addons.js
.storybook/config.js
package.json
yarn.lock

Toggle translations in storybooks, refs #2410

---

src/server/redirects.js

redirect pick_account to new faucet

---

src/app/components/modules/Header.jsx
src/app/components/modules/Header.scss

set header height for IE.

---

src/app/components/App.jsx
src/app/components/modules/SidePanel.scss
src/app/locales/en.json

add third party exchanges section to side panel menu

---

src/shared/HtmlReady.js
src/shared/HtmlReady.test.js

allow steemit.com in anchor links

---

README.md
package.json
webpack/debug.config.js

"closes" #2466 
this was very useful in my investigations for the state-leak issue, and want to make it available for future work.

add server-side debug command to package.json

---

src/app/components/modules/Settings.jsx
src/app/components/modules/Settings.scss
src/app/locales/en.json
src/app/locales/es.json
src/app/locales/fr.json
src/app/locales/it.json
src/app/locales/ko.json
src/app/locales/pl.json
src/app/locales/ru.json
src/app/locales/zh.json

Update settings page with new styling, formatting

---

src/app/locales/en.json

add a missing space in localized string

---

src/app/components/modules/Header/styles.scss

Fixes hamburger padding discrepency.

increase margin on hamburger

---

src/app/components/modules/Header/index.jsx

Account metadata for a profile page is not available on server side render...

do not load account meta server-side

---

src/app/components/App.jsx
src/app/components/pages/Post.jsx

fixes #2635 
- use lodash isEqual to compare query object
- change query propType from string to object

Fix App query PropType and object compare

---

src/server/app_render.jsx

this data is not used anywhere in the condenser codebase

remove user email from offchain data

---

src/server/api/general.js

refs https://steemit.slack.com/archives/C5ADW8RQQ/p1521030862000166

allow existing user record during create_user

---

src/app/utils/Phishing.js
src/shared/HtmlReady.js
src/shared/HtmlReady.test.js

do a phishing test using an in-repo list

---

src/app/components/cards/Comment.scss

Reverts steemit/condenser#2729
Bug:

Revert "Collapse Issue for Highlighted comment"

---

src/server/server.js

```
$ wrk http://localhost:8080/assets/app-9505931b1971f9a49a26.css -c 10 -t 2 -d 2m
Running 2m test @ http://localhost:8080/assets/app-9505931b1971f9a49a26.css
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    72.53ms   40.65ms 431.97ms   86.88%
Req/Sec    72.85     19.52   121.00     68.59%
17466 requests in 2.00m, 784.68MB read
Requests/sec:    145.44
Transfer/sec:      6.53MB
```
```
bc@zebrina:~/steemit/condenser$ wrk http://localhost:8080/assets/app-9505931b1971f9a49a26.css -c 10 -t 2 -d 2m
Running 2m test @ http://localhost:8080/assets/app-9505931b1971f9a49a26.css
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    27.15ms   33.89ms 236.93ms   81.94%
Req/Sec   394.31    136.71     1.14k    70.34%
94199 …
```

serve static assets much faster

---

config/custom-environment-variables.json
config/default.json
src/server/server.js

Closes #2809 Add docker tag and source commit data to healthcheck response

Add source commit and docker tag to healtcheck

---

src/app/components/all.scss
src/app/components/elements/SanitizedLink/index.jsx
src/app/components/elements/SanitizedLink/styles.scss
src/app/components/pages/UserProfile.jsx
src/app/locales/en.json

closes #2735
follows model of Memo badactor functionality

add SanitizedLink component that hides phishy links

---

config/custom-environment-variables.json
config/default.json
src/app/components/modules/TermsAgree.jsx
src/app/locales/en.json
src/app/redux/UserReducer.js
src/app/redux/UserSaga.js
src/app/utils/ServerApiClient.js
src/server/api/general.js

redo of #2850
un-reverts #2862 
closes #2560 
my original PR ignored a design spec; this one fixes up the design to fit the spec.
see changes in 3b779150ed9d8c334615f61fd9ea91254f10b209

un-revert & repair the TOS popup PR

---

src/app/components/modules/UserWallet.jsx
src/app/redux/UserReducer.js
src/app/redux/UserSaga.js

Fixes #2205 - (update) I'm seeing a ci/circleci: run-blackboxtest error looking at it.

use latest feed price for wallet value

---

src/server/server.js

This will keep files in memory instead of reading from disk for each request

Fix static cache settings

---

src/app/components/modules/Modals.jsx
src/app/components/modules/TermsAgree.jsx

do not show terms acceptance modal on TOS or Privacy pages

---

src/server/api/general.js

use const for accepted tos tag

---

src/app/help/en/tos.md

how to do in the future:
1. copy rendered html from google doc
2. replace existing `src/app/help/en/tos.md` file content with copied text
3. open in vim
4. run these commands:
```
:%s%^\([0-9]*\. [A-Z]\)%## \1
:%! fold -w 80
:%s% *$%%
```

update ToS to latest version

---

src/app/components/modules/Transfer.jsx
src/app/utils/ChainValidation.js

add a special validator for use in the transfers page

---

src/app/utils/VerifiedExchangeList.js

Replaces #2883 by @Smittyvb:
> This adds more exchanges, and puts the list in alphabetical order. See issue #2882.

Community - Add more exchanges

---

package.json
yarn.lock

closes #2929
who even uses sqlite3 with condenser? idk. hopefully this still works for them ;)

use sqlite3 version 4

---

src/app/help/en/welcome.md

Update welcome page

---

src/app/components/elements/ReplyEditor.jsx

Quick change to disable the advanced payout setting for comments in the working branch for advanced settings.

Community - Advanced Payout settings, disable for comments

---

src/app/utils/ExtractContent.js

fix arr length check

---

src/app/ResolveRoute.js
src/app/ResolveRoute.test.js
src/app/components/cards/TransferHistoryRow/index.jsx
src/app/redux/FetchDataSaga.js
src/app/redux/SagaShared.js
src/app/redux/stateCleaner.js
src/app/utils/GDPRUserList.js
src/app/utils/__mocks__/GDPRUserList.js
src/app/utils/steemApi.js
src/shared/UniversalRender.jsx

closes SD-310
new file `src/app/utils/GDPRUserList.js` stores usernames
404 user-related paths
prevent comments & their children from rendering

filter out certain users in a steem api wrapper

---

src/app/locales/en.json

Local PR for @TimCliff's #3020:
> This PR should be applied as close to the HF time as possible.
> Here is a screenshot of the new modal:
> 
> ![image](https://user-images.githubusercontent.com/20735105/45965202-81c31400-bfed-11e8-927e-2200b7c21567.png)
>

Closes #3019 Change Bandwith to RC

---

src/app/components/modules/SidePanel/index.jsx
src/app/help/en/faq.md
src/app/locales/en.json
src/app/locales/es.json
src/app/locales/fr.json
src/app/locales/it.json
src/app/locales/ja.json
src/app/locales/ko.json
src/app/locales/ru.json

[#3018] remove steemitshop from condenser.

---

src/app/assets/stylesheets/_themes.scss
src/app/components/App.jsx
src/app/components/App.scss
src/app/components/elements/Announcement.jsx
src/app/components/modules/Header/index.jsx
src/app/components/modules/Header/styles.scss
src/app/components/modules/Modals.jsx
src/app/components/modules/UserWallet.jsx
src/app/locales/counterpart/ja.js
src/app/redux/UserReducer.js
src/app/redux/UserSaga.js
src/server/server.js

allow user to close banner
update copy
also closes #3037

update HF banner

---

src/app/components/modules/Header/index.jsx
src/app/redux/UserSaga.js

disable announcement in a more effective way
todo (as mentioned in the comment):
use config to enable/disable

Disable banner for real

---

src/app/utils/DMCAList.js

added:
```
/sales/@grantcardone/get-cardone-university-for-free-2018-4-5-12-26-27
```

1878 - freshdesk

---

yarn.lock

Closes #3085
Replaces @jonching's #3057

Community - update steemscript

---

src/app/components/modules/SidePanel/index.jsx
src/app/locales/en.json
src/app/locales/es.json
src/app/locales/fr.json
src/app/locales/it.json
src/app/locales/ja.json
src/app/locales/ko.json
src/app/locales/pl.json
src/app/locales/ru.json
src/app/locales/zh.json

Add Businesses Accepting Steem link #2991

---

src/app/components/elements/Voting.jsx
src/app/components/modules/UserWallet.jsx

Closes #3101 
This really should be farmed out to steem-js when it supports this.

#3101 - fix estimated account value on wallet page

---

package.json
src/app/components/elements/Voting.jsx
src/app/components/modules/UserWallet.jsx
src/app/redux/RootReducer.js
src/app/utils/StateFunctions.js
yarn.lock

3106 eonwarped price per steem js fix

---

package.json
src/app/components/elements/Voting.jsx
src/app/components/modules/UserWallet.jsx
src/app/utils/StateFunctions.js
yarn.lock

Only for testing

---

src/app/components/modules/Header/index.jsx
src/app/components/modules/LoginForm.jsx
src/app/redux/UserReducer.js
src/app/redux/UserSaga.js

This differentiates initial login and active login, so it will not break the permissions page and the market page.

Fix active login

---

src/app/utils/BadActorList.js

Converted to a project branch from #3121

Add bad actor

---

src/app/assets/icons/pin-disabled.svg
src/app/components/cards/PostsList.jsx
src/app/components/elements/Icon.jsx
src/app/components/pages/PostsIndex.jsx
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js
src/server/utils/PinnedPosts.js

As a logged in user,
When I visit my Feed page,
I see pinned posts.
As a logged out user,
When I visit the All Trending page,
I see pinned posts.
As any user,
When I see a pinned post a second time,
The pin icon is greyed out.

Pinned post enhancements

---

src/app/utils/DMCAList.js

Adds dmca takedown #1062

---

src/server/index.js

Make server side use the server side steemd url

---

yarn.lock

From @tiotdev #3249:
> See issue #3248

Community - Update steemscript to 1.1.1

---

src/app/components/elements/GptAd.jsx

From @TimCliff #3064, closes #3021.

Community - Update FAQ for HF20 

---

config/default.json
src/app/components/elements/GoogleAd.scss
src/app/components/elements/GptAd.jsx
src/app/components/pages/Post.jsx
src/app/components/pages/PostsIndex.jsx
src/server/app_render.jsx
src/server/server-html.jsx
webpack/base.config.js

Replaces https://github.com/steemit/condenser/pull/3272 and includes https://github.com/steemit/condenser/pull/3276

GPT Bidding 2: Electric Boogaloo

---

src/app/components/cards/PostsList.jsx

Fixes a bug where the id for the child element of a list was incorrect.

Bug: Fix id for multiple pinned posts

---

src/app/redux/TransactionSaga.js

Resolves #3301 caused by #3286 (from community PR #2952 )

Add back substitution code at end of permlink generation

---

src/app/components/cards/MarkdownViewer.jsx
src/app/utils/Links.js
src/app/utils/SanitizeConfig.js

detect periods and dashes in dtube id, close #3304

Fix dtube id regex

---

src/server/server.js

A bit of a workaround, but this tackles the glaring issue of them not updating at all.
Closes #3306 but could be revisited someday.

Refresh pinned (featured) posts every five minutes

---

src/app/assets/icons/chevron-down-circle.svg
src/app/components/cards/Comment.jsx
src/app/components/cards/PostFull.jsx
src/app/components/cards/PostSummary.jsx
src/app/components/elements/Voting.jsx
src/app/components/elements/Voting.scss
src/app/components/elements/Voting.test.jsx

change flag to downvote

---

src/app/components/cards/PostFull.scss
src/app/components/elements/ReplyEditor.scss

From @quochuy #3063:
> Changing the width of editor preview to 50rem like PostFull

Community - Match width of editor preview and actual post

---

src/app/components/elements/Userpic.jsx

use steemitdev avatar for steemitblog

avatar override

---

src/app/assets/stylesheets/app.scss
src/app/components/modules/Settings.jsx

Closes #3289
- adds link to steemitwallet to update public profile
- fixes follows pagination CSS
- adjust settings page column handling
----
before
after

add link to update profile, css fixes

---

src/app/components/elements/BiddingAd.jsx
src/server/server-html.jsx

Introduced by https://github.com/steemit/condenser/pull/3318
Before:
After:

Bug: Fix excessive header padding

---

config/default.json
src/app/components/pages/Post.jsx

Since we punted on moving `top-navi` to bidding we're going to move `post-above-comments` to bidding instead.

Update Slot Bidding Again

---

src/app/components/cards/Comment.jsx
src/app/components/cards/PostFull.jsx
src/app/components/elements/ContentEditedWrapper/index.jsx

From @quochuy #3337:
> Fixes #1146
>
> ![Screen Shot 2019-05-10 at 10 28 49 pm](https://user-images.githubusercontent.com/310654/57527658-946b3d00-7373-11e9-9bc6-91c9d814769d.jpg)
> 
> ![Screen Shot 2019-05-10 at 10 31 23 pm](https://user-images.githubusercontent.com/310654/57527670-9c2ae180-7373-11e9-9972-27fcd2c876ac.jpg)
>

Community - Mark when a post/comment has been edited

---

src/app/redux/TransactionSaga.js
src/app/redux/TransactionSaga.test.js

From @quochuy #3328:
> Fixes #3278
>
> Can be tested on JSFiddle:
> https://jsfiddle.net/jda9p5xf/

Community - Shorten permlinks from nested comments

---

config/default.json
src/app/components/App.jsx
src/app/components/elements/BiddingAd.jsx
src/app/components/elements/GptAd.jsx
src/app/components/modules/Header/index.jsx
src/server/server-html.jsx

- Hide ad when scrolling
- Fix ad type
- Stop forcing renders and instead render based on state
- Fixes https://github.com/steemit/condenser/issues/3281

Cleanup header

---

src/app/utils/GDPRUserList.js

Request from Bitfinex on trademarks for Bitfinex and Finexbox

Block blog from displaying due to trademark infringement request

---

src/app/components/elements/BiddingAd.jsx
src/app/components/elements/GptAd.jsx
src/app/components/modules/Header/index.jsx

- Added event listeners to the Freestar GPT internals.
- Added additional event type 'impressionViewable' as suggested by @quochuy
Fixes https://github.com/steemit/condenser/issues/3281, https://github.com/steemit/condenser/issues/3385

Fix header covering content

---

src/app/components/pages/Post.jsx

This slot wasn't rendering previously.

Fix Comment Slot

---

src/app/utils/DMCAList.js

20190708 dmca

---

src/app/assets/stylesheets/_themes.scss
src/app/assets/stylesheets/foundation-overrides.scss

From @quochuy #3431:
> Fixes #3422: add theme to modals

Community - fix modals in night mode

---

src/app/components/cards/Comment.jsx
src/app/locales/en.json

From @quochuy #3433:
> Closes #3005: don't hide own comments even if flagged

Community - don't hide own flagged comments

---

src/app/components/elements/GptAd.jsx

Reverts steemit/condenser#3427

Revert "Make Slot Id Slightly More Unique"

---

src/app/components/elements/GptAd.jsx

Reverts steemit/condenser#3444

Revert "Revert "Make Slot Id Slightly More Unique""

---

config/default.json
src/app/components/cards/PostsList.jsx
src/app/components/modules/Header/index.jsx
src/app/components/pages/Post.jsx
src/app/components/pages/PostsIndex.jsx
src/app/utils/GptUtils.js
src/server/app_render.jsx
src/server/server-html.jsx

Work in progress. Need to figure out how to gate the banner header ad based on the post tags.
- Google doesn't like serving ads on NSFW content.

WIP: Disable ads on NSFW Content

---

src/app/components/pages/Post.jsx

Remove Gummed Up Ad

---

src/app/components/pages/Post.jsx

Seems like the sidewall ad may have been the real cause of the UI issues.

Re-add GumGum; Remove Sidewall

---

src/app/components/cards/PostsList.jsx
src/app/components/elements/GptAd.jsx
src/app/components/modules/Header/index.jsx
src/app/components/pages/Post.jsx

- Adds NSFW targeting to pubads so that ads can be turned off by advertiser.
- Fixed a missing key bug on Posts that had been complaining

Add NSFW Targeting

---

src/app/components/pages/Post.jsx

Didn't expect this to grab onto images.

Scrape the gum off the images

---

src/app/components/elements/GptAd.jsx
src/app/components/modules/Header/index.jsx

- Previous attemps were not good enough for the Google.

Yet Another Attempt to Hide Ads on NSFW Pages

---

src/app/components/elements/Announcement.jsx
src/app/redux/UserReducer.js

The time has come to warn everyone about the exciting upcoming changes to the Steem blockchain

Enable Announcement Banner for HF21

---

src/app/assets/ads.txt
src/app/components/cards/PostsList.jsx
src/app/components/elements/GptAd.jsx
src/app/components/modules/Header/index.jsx
src/app/components/pages/Post.jsx
src/app/components/pages/PostsIndex.jsx
src/server/server-html.jsx

Upgrading to a real ad network.

Replace FS with BSA

---

src/app/components/elements/Announcement.jsx

Let everyone know HF22 was a success

Update announcement banner

---

src/app/components/elements/GptAd.jsx
src/app/redux/FetchDataSaga.js

Stop refreshing every ad on load

---

src/server/server-html.jsx

- Allows for realtime ad performance monitoring.

Add BSA Tracking Script

---

src/app/components/elements/GptAd.jsx
src/app/redux/FetchDataSaga.js

It's not good enough to check if `window.optimize` is defined--we also need to make sure it's ready for action.

Bug: Fix an exception caused during page load

---

src/app/components/elements/SubscribeButton.jsx
src/app/components/elements/SubscribeButtonContainer.jsx
src/app/components/pages/PostsIndex.jsx

This will allow a user to subscribe or unsubscribe to a community.
Screenshots:
Issue:
- Layout needs some love.
Closes #3494

Add subscribe/unsubscribe button to community index

---

src/app/utils/BadActorList.js

From @themarkymark-steem #3527:
> Add bittriex fake account

Community - Update BadActorList.js

---

src/app/components/modules/SidePanel/index.jsx
src/app/locales/en.json

Link to new self serve portal.

Update advertise link

---

src/app/components/cards/CategorySelector.jsx
src/app/components/elements/ReplyEditor.jsx

- cherry-picked cleanup commit from bridge-api
- add MAX_TAGS const, Set -> OrderedSet

increase max tags to 8

---

src/app/components/pages/Privacy.jsx

Update privacy policy to allow mailing of newsletters

---

src/app/components/cards/PostFull.scss

fix iOS 13 scrolling bug

---

src/app/components/elements/ReplyEditor.jsx

Reverts steemit/condenser#3563

Revert "Community - fix clear draft on posting"

---

src/app/components/elements/ReplyEditor.jsx

From @eonwarped #3565:
> Fixes issue with #3557. Verified locally.

Community - fix clear draft on posting (Take 2)

---

src/app/utils/CanonicalLinker.js
src/app/utils/CanonicalLinker.test.js

restore canonical urls, with whitelist

---

src/app/components/modules/CommunitySettings.jsx

community settings form validation

---

src/app/components/elements/CommunityPaneMobile.jsx
src/app/components/pages/PostsIndex.jsx
src/app/components/pages/PostsIndex.scss

display community pane on smaller devices

---

src/app/components/cards/NotificationsList.jsx
src/app/components/elements/ClaimBox.jsx
src/app/components/pages/UserProfile.jsx

add claimbox component, refs #3545

---

src/app/components/cards/PostFull.jsx
src/app/components/elements/PageViewsCounter.jsx

remove pv_counter from postfull

---

src/app/ResolveRoute.js
src/app/ResolveRoute.test.js
src/app/RootRoute.js
src/app/components/pages/Rewards.jsx
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js
src/app/utils/steemApi.js

3619 im rewards page

---

src/app/components/cards/PostsList.jsx

Returning an array allows you to return multiple components without wrapping them inside a <div>

Fix broken styling on the post preview before an ad in the post list

---

src/app/components/modules/Header/index.jsx
src/app/components/utils/ReactMutationObserver.jsx

3385 fix ad hiding header

---

src/app/components/all.scss
src/app/components/cards/NotificationsList.jsx
src/app/components/cards/NotificationsList.scss
src/app/components/elements/DropdownMenu.jsx
src/app/components/modules/Header/index.jsx
src/app/components/modules/Header/styles.scss
src/app/components/pages/UserProfile.jsx
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js
src/app/redux/PollingSaga.js
src/shared/RootSaga.js

3627 im unread notifications

---

src/app/components/pages/CommunitiesIndex.jsx

- Display a loading indicator when loading the communities list
- Remove unused code

Fix loading indicator not showing on community index

---

src/app/components/modules/Header/index.jsx

Adding links to posts, comments and payout from profile menu

---

src/app/components/elements/ReplyEditor.jsx

add default nsfw tag if community is nsfw

---

src/app/components/modules/Header/index.jsx
src/app/components/utils/ReactMutationObserver.jsx

From @quochuy #3635:
> Using MutationObserver to detect when the header ad is rendered and resize the headroom.
This should provide a more permanent fix.

Community - fix ad hiding header

---

src/app/components/cards/MarkdownViewer.jsx
src/app/utils/Links.js
src/app/utils/Links.test.js
src/shared/HtmlReady.js

Added tests for Links.js
Fixes for passing tests
Fixes for warnings for webkitallowfullscreen and allowFullScreen in iframe tag
Fixes for eslint warning for missing title attribute in iframe tag

Fixes from code review

---

src/app/components/elements/CommunityPane.jsx
src/app/components/pages/CommunitiesIndex.jsx
src/app/components/pages/CommunitiesIndex.scss
src/app/components/pages/PostsIndexLayout.jsx
src/app/locales/en.json
src/app/redux/GlobalReducer.js

3666 community leadership views

---

src/app/components/cards/TagInput.jsx
src/app/locales/en.json

add validation for multiple hive- tag inputs

---

src/app/ResolveRoute.js
src/app/ResolveRoute.test.js
src/app/components/cards/NotificationsList.jsx
src/app/components/cards/SubscriptionsList.jsx
src/app/components/modules/Header/index.jsx
src/app/components/pages/PostsIndex.jsx
src/app/components/pages/PostsIndexLayout.jsx
src/app/components/pages/UserProfile.jsx
src/app/locales/en.json
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js
src/shared/UniversalRender.jsx

Closes #3649 
TODO:
> list_all_subscriptions(account) is the call to use, but the backend needs to return role/title data.

3649 im profile communities tab

---

src/app/components/cards/NotificationsList.jsx
src/app/components/cards/NotificationsList.scss
src/app/components/elements/ElasticSearchInput/SearchInput.story.jsx

Closes #3652
Also - adds an avatar for notification participants.

3652 notifications design

---

src/app/components/elements/ReplyEditor.jsx

- Fix: If you drop you images by multiple batches, the index number in  temporary didn't increment
- Fix: the latest batch of files replaces the current ones

Fixes to the multiple image uploads

---

src/app/assets/stylesheets/_themes.scss
src/app/components/cards/NotificationsList.jsx
src/app/components/elements/CommunityPane.jsx
src/app/components/elements/CommunityPaneMobile.jsx
src/app/components/modules/Dialogs.jsx
src/app/components/modules/PostAdvancedSettings.jsx
src/app/components/pages/UserProfile.jsx
src/app/redux/FetchDataSaga.js

3614 im notifications modal community

---

src/app/ResolveRoute.js
src/app/ResolveRoute.test.js

allow categories in url with 1 letter, refs #3691

---

src/app/assets/stylesheets/_themes.scss
src/app/assets/stylesheets/foundation-overrides.scss

fix modal text-color on mbile

---

src/app/components/cards/SubscriptionsList.jsx
src/app/components/elements/ElasticSearchInput/index.jsx
src/app/components/modules/Header/index.jsx
src/app/components/pages/CommunitiesIndex.jsx
src/app/components/pages/SearchIndex.jsx
src/app/redux/CommunitySearchReducer.js
src/app/redux/CommunitySearchSaga.js
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js

3651 search communities

---

src/app/components/pages/PostsIndex.jsx

3697 show users community feeds mobile

---

src/app/components/cards/PostsList.jsx
src/server/server-html.jsx

This reverts commit de6cb981bf4f012764856a7cd8b087ca7cbd1f31.

Revert "disable plist ads"

---

src/app/components/elements/SearchInput/styles.scss

In organization version of: https://github.com/steemit/condenser/pull/3707

Quochuy search bar css

---

src/app/components/pages/PostsIndex.jsx
src/app/components/pages/Topics.jsx

mobile communities native select

---

src/app/assets/stylesheets/foundation-overrides.scss
src/app/components/modules/Dialogs.jsx

3723 moderation log close button

---

src/app/components/elements/ReplyEditor.jsx

Closes #3717 #2247 
Bug was reproducable:

3717 post max length error

---

src/app/redux/UserSaga.js

Closes https://github.com/steemit/steempunks/issues/559

Bug - uncaught error when username is not valid.

---

src/app/redux/UserReducer.js
src/app/redux/UserSaga.js

disable communities announcement

Disable communities announcement

---

package.json
src/app/components/pages/CommunitiesIndex.jsx
src/app/redux/FetchDataSaga.js
yarn.lock

communitys search 

---

config/dev.json

remove dev json

---

src/app/components/cards/NotificationsList.jsx
src/app/components/cards/NotificationsList.scss
src/app/locales/en.json

In organization version of: https://github.com/steemit/condenser/pull/3734

Quochuy notification filters

---

src/app/components/elements/SteemMarket.jsx

pending my changes to: https://github.com/steemit/steem-market being merged and deployed.
closes #3779

add tron to SteemMarket.jsx

---

src/app/help/en/faq.md

Remove exchange  that do not support steem
remove unavailable links

Remove unsafe 3rd party links

---

src/app/components/pages/Rewards.jsx
src/app/redux/FetchDataSaga.js
src/app/redux/GlobalReducer.js

add account count to rewards page

---

src/app/assets/stylesheets/markdown.scss
src/app/components/App.scss
src/app/components/cards/Comment.scss
src/app/components/cards/PostFull.scss
src/app/components/elements/AdSwipe.jsx
src/app/components/elements/AdSwipe.scss
src/app/components/elements/AuthorDropdown.scss
src/app/components/elements/DropdownMenu.scss
src/app/components/elements/VerticalMenu.scss
src/app/components/pages/Post.jsx
src/app/components/pages/PostsIndexLayout.jsx

* fix vertical menu float out in the mobile screen
* fix #3821 
* fix markdown image caused element overflow in the mobile screen.
* fix author dropdown menu and comment order dropdown menu overflow in the mobile screen.

Fix issue 3821

---

.eslintrc
config/custom-environment-variables.json
config/default.json
package.json
src/app/Main.js
src/app/utils/ActivityTracker.js
src/app/utils/Links.js
src/app/utils/ServerApiClient.js
src/server/app_render.jsx
src/shared/constants.js
yarn.lock

To trace the third activities.

activity tracker

---

src/app/utils/ActivityTracker.js
src/app/utils/ServerApiClient.js

1. temp remove refferrer condition
2. add ua info

Temp remove refferrer

---

src/app/components/cards/Comment.scss
src/app/components/cards/DraftSummary.jsx
src/app/components/cards/DraftSummary.scss
src/app/components/modules/PostTemplates.jsx
src/app/components/modules/PostTemplates.scss
src/app/components/pages/Post.jsx

post summary bug fix

---

src/app/components/pages/Post.scss

fixed issue #3907

---

src/app/components/modules/Header/index.jsx

Fixed an error when clicking the search button on mobile web.

---

src/app/components/modules/Header/index.jsx

It was working fine locally and I am not aware of the issue.
However, in production, the issue was still not resolved.
Please review it once more.
Thank you. @ety001

Issue #3906 has not been resolved, this is my mistake. 

---

src/app/utils/Links.js
src/app/utils/Links.test.js

This PR supports the youtube short URL format, and tested locally. 
This PR adds a unit test - and closes #3947

Support youtube short URL

---

src/app/components/pages/Privacy.jsx
src/app/help/en/tos.md

remove redundant words in comment

chore: remove redundant words in comment
