steemit/condenser

- app/components/elements/TagList.jsx
Uniquely identify each child by assigning it a key.
> Fix unique ID bug in tag mapping

- app/components/modules/BlocktradesDeposit.jsx
A quick UX tweak, to enable the numeric keypad to pop up on mobile (instead of the normal qwerty keyboard).
> Update BlocktradesDeposit.jsx input type="tel"

- README.md
It's not stated anywhere on the README, so I added it to the dependencies, and suggested nvm (which is pretty important for anyone who works on more than one node project)
> Add note about Node 6.3 to the README

- app/components/pages/Witnesses.jsx
After talking with a few people, there was some confusion as to whether
votes were actually being applied to people outside of the top 50. This
change adds those users below the input box, and also lets them upcast
their votes by clicking the button.
- The additional witnesses are loaded off the current user's `witness_votes` profile field. 
- Any witnesses in the top 50 are filtered out.
- Entering a username and voting will add the username to the list below.
- Clicking the blue vote will uncast the vote, removing the user.
> Show the additional witnesses you have voted for outside of the top 50

- app/components/pages/Witnesses.jsx
Spent a little time this evening tinkering with the witnesses page again. I've made some modifications including:
- The witness URL has been added as a link to the right most column. 
- A small description has been added to the top of the page with how many remaining votes you have left along with the maximum.
- I thought some visual distinction and columns would do it justice, so I converted it into a table.
- Mobile optimizations for the "additional witnesses" section.
I'm curious to know what other type of basic information should be added to this page. I choose not to add the price feed, misses, blocks and more advanced user information just to help avoid confusion.
> Added witness url + remaining votes

- app/components/cards/PostFull.jsx
[@bitcoiner posted this feature request](https://steemit.com/tag/@bitcoiner/steemit-improvement-idea-give-a-link-to-the-parent-post) in response to some of the links I've been using on steemstats.com. These links leave steemstats.com and go directly to a reply, like so:
[https://steemit.com/tag/@jesta/re-bitcoiner-steemit-improvement-idea-give-a-link-to-the-parent-post-20160822t051520448z](https://steemit.com/tag/@jesta/re-bitcoiner-steemit-improvement-idea-give-a-link-to-the-parent-post-20160822t051520448z)
It's been incredibly useful to leave steemstats, immediately land on a reply, and be able to write a response. The only pain point is that there's no navigation on this page like you would get on reddit. So I propose the following change if `content.depth > 0`:
The two links will …
> Added conditional header to posts for posts with depth > 0

- app/components/pages/Witnesses.jsx
It was not my intent to make the the witness page go full width. This PR moves the table into the grid/column layout that and uses the `small-collapse` class on the row to avoid impacting mobile layout.
> Fixing desktop rows on witness page

- app/components/all.scss
- app/components/pages/TagsIndex.jsx
- app/components/pages/TagsIndex.scss
This is slight UI/CSS improvement for the filter search input on the tag index page.  The input margins where being overridden by !important from the parent.  The search input is also improved to be responsive for mobile/tablet devices.
> Input filter style fix

- app/components/cards/PostFull.jsx
I believe my last commit to conditionally show and hide the direct link actually broke the direct link. This fixes it.
> fixed direct parent link

- app/assets/stylesheets/foundation-overrides.scss
Removing outlines on links hampers the accessibility of the site for people with impaired vision etc. Thus it is important not to disable outlines as they are there for a reason.
I'm creating this pull-request at the same time as I'm publishing a post on steemit with a list of changes that should be implemented to try and make steemit as accessible as possible, so sadly it isn't of the highest quality. I'm making this mostly as a suggestion and to raise awareness.
Link to post:
https://steemit.com/accessibility/@novium/steem-it-a11y-accessibility-project-make-steem-accessible-for-everyone
> A11y - outline: none on all links

- shared/HtmlReady.js
A small little edit so no errors are made if given a blank string. I was playing with this module directly for a project I'm working on and noticed that empty string caused errors because `doc` would be undefined when calling `DOMParser.parseFromString` with a blank string.
So this checks if doc is defined before calling `serializeToString` and within `proxifyImages` before the forEach loop.
> No errors if HtmlReady is given a blank string

- app/utils/SanitizeConfig.js
Due to screenreaders not being able to just instantly recognize an image and it's contents alt-tags are perfect, no need of removing them :)
If I correctly understand the code the it should sanitize the alt-tag, but please double-check that before merging!
(Part of the [A11y project](https://steemit.com/steemit/@novium/steem-it-a11y-project-second-pull-request-fixing-image-alt-tags))
> A11y - Fix alt text on images

- app/components/modules/Header.jsx
- Ensure all titles are always first letter capitalized (consistency and user readability)
- Further tweaks to page titles with no category/tag selected
> Further SEO Page Title Refinements #332

- app/components/cards/CategorySelector.jsx
- app/components/elements/ReplyEditor.jsx
Update validation to allow users who enter category tags with # hashtag when posting/editing.   Parsing is done on creation to strip hashtag symbols.
> Category validate update

- app/components/modules/LoginForm.jsx
This is in response to a dialog in Steemit Chat #help channel.
The issue arised from the check on the authType: _vote_ was being matched in _account_witness_vote_.
Corrected:
> Fix Witness Vote Login Prompting for Posting Key

- app/components/cards/Comment.jsx
- app/components/elements/ReplyEditor.jsx
I've been testing this extensively, but I'd like to get it merged into develop soon so any issues can be caught quickly.
Main changes:
- `<html>` is no longer used during the editing process. It's stripped in `componentWillMount` and the `rte` flag is set appropriately. It's only added back during `reply()`.
- No longer updating `rte_value` in `componentWillReceiveProps`. I believe this was a workaround and it should no longer be required.
I removed the `if(editorData.formId === formId)` check in [ReplyEditor.jsx#L116](  https://github.com/steemit/steemit.com/blob/e9574285d6761f330e4e1e801fc4ed2e4839f359/app/components/elements/ReplyEditor.jsx#L116) as it seems it could never be false.. let me know if this is not the case.
> Refactor of ReplyEditor #185

- app/components/cards/PostSummary.jsx
- app/components/cards/PostsList.jsx
- app/components/pages/UserProfile.jsx
This will allow users to go to a blog and be able to easily tell which posts are from the author and which were resteemed.
The pattern from the feed was followed.
Here is an example of what it is currently:
Here is what it will look like:
> Show Resteemed on Blog

- app/components/modules/BlocktradesDeposit.jsx
- app/components/pages/Witnesses.jsx
Some witnesses set their url with an external links. This will allow users to view them from the Witnesses page (instead of directing to steemit.com homepage due to it not found).
In addition, added a space between the two sentences:
Also, added `target=_blank` to another page's link that had showed the extlink icon.
> Fix for External Witness URLs to Open in New

- app/utils/Links.js
- app/utils/Links.test.js
- `urlChars` must not end with  a `.` or `,`
- `domainPath` must not end with a `\` or `.`, or `_`
Any other chars to blacklist? This is a minimal set which resolves #424
> URL regex #424

- app/components/elements/ReplyEditor.jsx
changes:
- `<html>` wrapper is added/stripped only when getting passed from/to the serializer
- posts beginning with `<p>` tag don't engage the RichtextEditor (but they still render as HTML)
- ability to convert from markdown mode into Editor mode* (experimental)
- ability to switch between Editor / Raw mode*
- ensure that non-html posts do not contain `<html>` tag anywhere
---
\* effectively disabled in the UI. to test, change `!body.value && isStory` to `isStory` on line 307
> html mode handling #185

- app/components/elements/Voting.jsx
This tmpfix can be removed when https://github.com/steemit/steem/issues/546 is resolved.
It fixes the following behavior:
> do not display invalid cashout_time #532

- app/components/pages/UserProfile.scss
For issue #624
With a small browser width like those on mobile, the Joined Date is displayed as follows:
After fix:
A CSS rule from before the user pics were implemented needed to be removed. In the past, this was to shrink the banner div as the h2 was responsively shrunk too.
> Fix joined date display

- app/components/pages/UserProfile.jsx
- app/redux/GlobalReducer.js
Relevant backend change: https://github.com/steemit/steem/commit/b7328bb0161b1efb97a8ab9e0798344f4114f272
This allows us to test steem/develop while maintaining compatibility with steem/master.
> add support for renamed API key, with backwards compatibility

- app/components/elements/UserList.jsx
- app/components/pages/UserProfile.jsx
This fixes follows API for shared-db while maintaining backwards compatibility
This can be merged in the frontend now, but follows in shared-db will be broken until https://github.com/steemit/steem/pull/577 is merged in
> update follows api logic with backwards compat for share-db upgrade

- app/components/elements/DropdownMenu.jsx
Currently when a user clicks a dropdown label (e.g. `3 votes`) to open the menu, then clicks it again, it cancels out the hide event. This restores the expected behavior.
> fix clicking label to hide dropdown

- app/components/elements/Follow.jsx
- app/components/elements/UserList.jsx
- app/components/pages/UserProfile.jsx
- app/redux/FollowSaga.js
1) `loading` prop was broken in `app/components/elements/Follow.jsx`, causing "Follow" and "Mute" to never show up for user dropdowns
2) revert shared-db follows api compat logic
3) force-convert incoming `what` strings back to Lists. steemd API will revert back to the old format after rc1.
> Fix follow loading status, and invert shared-db follows api fix

- app/components/elements/DropdownMenu.jsx
- app/components/elements/VerticalMenu.jsx
mousedown was used for the #641 fix because of an onClick conflict.
It appears the conflict was due to `closeMenu` in `VerticalMenu` -- as far as I can tell, we do not need this logic.
> switch to using onclick, remove menu close event. resolves #722

- README.md
- app/components/elements/DepthChart.jsx
- app/components/modules/ConfirmTransactionForm.jsx
- app/components/pages/Market.jsx
- app/components/pages/Market.scss
- app/redux/Transaction.js
- app/redux/TransactionSaga.js
Also includes an update to the README for Ubuntu 16.x
> Market bug fixes

- app/components/pages/Market.jsx
- app/components/pages/Witnesses.jsx
- app/redux/MarketSaga.js
I made the state.market.account object immutable as well which is why Market.jsx needed an update.
> Also update global account state on MarketSaga get_accounts, fixes #437

- app/components/modules/LoginForm.jsx
- app/components/modules/Transfer.jsx
@valzav asked me to add the @ prefixes to account inputs and I noticed there was room for improvement in the asset selection dropdown so I restyled it in the same vein.
The LoginForm would not set the initial value for the account for users logging in with private keys, so I've added that to the connect method initialisation. The account input also gets an @ prefix.
> Login form transfer updates

- app/redux/Transaction.js
changes the message from
> Account registered by another account requires 10x account creation fee worth of Steem Power before it can be powered down.
to
> Account requires 10x the account creation fee in Steem Power (approximately 300 SP) before it can power down.
Now that SP is more stable the account creation fee should not fluctuate so much. Once https://github.com/steemit/steem/issues/695 is implemented, we will have the exact value in the message.
> clarify power down error message #665

- app/components/cards/Comment.jsx
- app/components/pages/Post.jsx
- added ability to sort comment by upvotes
- remove `updated` and `active` comment sort orders (anyone see a reason to keep them?)
> ability to sort comments by upvotes #808

- app/components/elements/Userpic.jsx
Comment thumbnails(and also profile page thumnail) now match sharpness of profile snippet image quality on retina and 4k displays.
New example below:
> 914 user thumbnails

- app/components/cards/PostSummary.jsx
Reference: https://github.com/steemit/steemit.com/pull/940/files
The crop bounds was 2:1 for thumbnails to account for cases of tall images. The current CSS-based cropping attempts to fit images widthwise -- when the bounding box is more of a square, tall images become very low res and in some cases stretched out.
@mcifani the example image URLs you listed all had a height that was less than 2x the width, so there is no difference in the generated image. But it does make an important difference for images which do not fit this case.
> restore thumb ratio for crops #940

- app/components/elements/Author.jsx
allows non-logged in users to engage & see more information about authors/commenters
> show Author dropdown for non-logged in users

- shared/UniversalRender.jsx
This addresses a few route issues.  Examples below. 
1.  @ats-david/transferss - all invalid user pages now properly 404(no spinning status).  
2.  @ats-david/a-walk-in-the-park-my-journey-through-images-volume-ii-nothing-here - all invalid short posts now properly 404(no spinning status)
3. This all preserves short post url linking
> #844 protect for invalid user pages allow for short post urls

- app/components/modules/Header.jsx
- app/utils/ExtractContent.js
- app/utils/ExtractMeta.js
This is a revamp for meta, seo improvements on profile pages(and site wide pages) for serps. 
Example of current google result for "neil strauss" steemit profile page. 
New profile improvements:
A. Title's will now read with meta name(if available). Example: "Neil Strauss (@neilstrauss)"  
B. User profile pages now have unique meta descriptions(capped at 170 char).  Instead of showing random text profile serp results will now reflect a username and meta name and about. 
C. User profile/and children now have meta tags. 
D. User profile pages have unique twitter card og tags.  If users share their profile they will have their profile image and name in the share card. 
Examples:
Current profile meta state:
New profile meta state:
New steemit site wide improvements:
A. Meta Description is now …
> 988 revamped profile meta

- app/components/cards/PostSummary.jsx
- app/components/elements/Voting.jsx
This pull request updates the UI so that flagged posts do not stand out compared to non-flagged posts.
**Reasoning:**
With the current implementation of "flags" and "downvotes" being combined into the same function, users receiving "downvotes" for non-abusive reasons such as disagreement on rewards has been causing a lot of controversy. Part of the reason is because the interface shows the post as 'flagged' whenever it receives a downvote, which makes the post seem 'bad' compared to non-flagged posts, even if the poster did nothing 'wrong'.
The main argument against this change will be that users can no longer easily identify posts that have been flagged for abusive reasons. While this is true, the current implementation of the flag/downvote at a blockchain level does not provide a good …
> Do not show how many flags a post has received

- app/components/App.jsx
The "Steemit Chat" link is a frequently used link by many users. This PR moves the "Steemit Chat" link higher in the menu, so it is easier to get to.
> Move the "Steemit Chat" link higher in the main menu

- app/components/pages/Witnesses.jsx
The witness voting proxy is an excellent feature to have in the GUI, but it is a feature that is only useful to a subset of users. Having at the top of the witness voting page does not seem like the best placement, since (hopefully) the "average" user is going to want to be involved in the witness voting process and vote for witnesses themselves.
This pull request moves the witness voting proxy to the bottom of the witness voting page.
I have verified that the functionality still works as expected when placed at the bottom of the page.
> Move witness proxy voting to the bottom of the witness voting page

- app/help/en/faq.md
In pull request https://github.com/steemit/condenser/pull/1106 sample categories were used as a proof of concept. In the larger FAQ update that @pfunks and I are working on, we will add a lot more content and organize everything into categories. For now, this PR is just removing the 'proof of concept' categories, so the PR with the table of contents can be used without including the fake categories. (@valzav to review)
> Remove sample categories from FAQ TOC

- app/components/modules/UserWallet.jsx
> fix incorrect arr index access in claim rewards dialog

- app/components/elements/Voting.jsx
It would be more clear if it read "Potential Payout X in 8 hours, *then* Promotion Cost X"
> Move promotion cost below payout date for clarity

- app/components/cards/TransferHistoryRow.jsx
Before
Claim rewards: 0.000 SBD, 0.000 STEEM, and 1.300 STEEM POWER	
Claim rewards: 0.856 SBD, 0.000 STEEM, and 6.923 STEEM POWER
After
Claim rewards: 1.300 STEEM POWER	
Claim rewards: 0.856 SBD and 6.923 STEEM POWER
> don't show empty values for claim op

- app/components/cards/PostsList.jsx
- app/components/cards/PostsList.scss
- app/components/modules/Header.scss
- app/components/modules/TopRightMenu.jsx
- app/components/modules/TopRightMenu.scss
- app/locales/en.js
- app/locales/es.js
- app/locales/es_AR.js
- app/locales/fr.js
- app/locales/it.js
- app/locales/jp.js
This PR fixes some issues with the clickable area of some of the icons in the top header. In particular the back arrow button in the post overlay mode was very hard to hit, I've modified it so the clickable area is bigger and it includes a 'back' text making it look very similar to the standard iOS back button.
The clickable area of the user icon, search magnifying glass and the hamburger menu have also been increased.
> Header improvements

- app/components/pages/Witnesses.jsx
There are two places on the witness voting page where users can manually enter a username (outside the top 50, and proxy voting). This PR adds the @ symbol in front of the two text boxes, which is consistent with the other places on the site that usernames are entered (such as the transfer page).
Screen Shot:
> Add @ symbol to witness voting page

- README.md
This PR updates and clarifies the condenser install instructions.
- Added step to verify NVM is installed.
- Changed config file from steem-example.json to default.json.
- Added quit/exit commands where appropriate.
- Added step to update ~/condenser/db/config/config.json with the mysql password.
- Clarified the step at the end to know when condenser is running.
- Updated the port number to be based on whatever is output as the port number condenser is running on.
> Updates to README.md Install instructions

- app/components/pages/PostsIndex.jsx
- app/locales/en.js
- app/locales/es.js
- app/locales/es_AR.js
- app/locales/fr.js
- app/locales/it.js
- app/locales/jp.js
- app/locales/ru.js
When a new user logs in and views their feed and it is empty, it shows links to get them started. This pull request makes the following changes:
1. Renames the 'welcome page' link to the 'quick start guide'.
2. Moves the welcome page / quick start guide link up to be the second link.
3. Replaces the link to the 'the-missing-faq-a-beginners-guide-to-using-steemit' post with a link to the actual FAQ.
> New feed link update

- server/requesttimings.js
- server/server.js
This will log requests that take longer than 150ms to complete and includes the method and path of the request.
> add request timing logging to condenser

- app/utils/BadActorList.js
Name of exchange deposit address on a different platform. User could use this by mistake thinking the same name is used here.
> Add account to bad actor list

- app/utils/BadActorList.js
The coinpayments.net payment gateway uses the 'coinpayments.net' account. Some users have been sending coins to coinpayments by mistake.
> Update to bad actor list coinpayments is not coinpayments.net

- app/components/App.jsx
- app/components/modules/UserWallet.jsx
- Updates the existing STEEM and SP "Buy" links to prepopulate the BlockTrades "Send" and "Receive" coin types with the appropriate coins ({BTC}, {STEEM, STEEM POWER}) depending on which link is clicked. 
- Adds a "Sell" option for STEEM.
- Adds a "Buy" and "Sell" link for SBD.
[Edit] link to Steemit discussion post: https://steemit.com/steemdev/@timcliff/condenser-pull-request-submitted-new-blocktrades-buy-sell-options-via-the-steemit-com-wallet
> Update wallet with new BlockTrades options

- app/components/cards/PostsList.scss
When a post is shown as a modal webkit redraws the entire post body on scroll, making it incredibly sluggish for longer posts with many photos. This fixes that by forcing the post container into layer backing with a null transform.
> Fix repaint of modal post on scroll

- app/components/App.jsx
- app/components/modules/UserWallet.jsx
This pull request updates the STEEM, SP, and SBD "Buy" links to pre-populate the "Your receive address" value on the BlockTrades interface with the account name of the currently logged in user. 
For the main menu link, it will use an empty-string value if the user is not currently logged in.
> BlockTrades "Buy" Links - Update to use the currently logged in user's account name

- app/components/elements/Voting.jsx
- app/redux/User.js
- app/redux/UserSaga.js
The current vote slider checks the amount of SP a user has, but it does not take into account delegation. This PR changes it to look at the net SP balance (vesting_shares - delegated_vesting_shares + received_vesting_shares).
> Check delegation when determining SP for showing vote bar Fixes #1441

- app/Main.js
- app/utils/BrowserTests.js
- config/custom-environment-variables.json
- config/default.json
- server/index.js
This patch adds config options for setting a custom chain id and address prefix. I also had to update the browser tests for it to run.
> Allow condenser to run against different chains

- src/app/help/en/faq.md
We came to the conclusion of using the tag 'portugues' to gather all speakers of the Portuguese language
> Added portuguese tag in Faq

- src/app/utils/ExtractContent.js
#1586 The regular expression for removing block quotes from .desc was a little too aggressive.
Assumption in the fix is that we're only concerned with a block quote at the *beginning* of a post (behavior introduced in #928 )
Before:
After:
> 1586 update blockquote extractor for ExtractContent .desc response attr

- src/app/components/elements/DepthChart.jsx
https://github.com/steemit/condenser/issues/1455
fix bad exponents in highcharts yaxis label formatter. Keep numeric precision at increments of 1000 above 10k.
Before:
After:
> 1455 market depth chart y axis

- README.md
the current README recommends installing global deps for running sequelize; this isn't necessary, and it works out-of-the-box with already-defined dependencies when you use `yarn exec` -- this makes local dev easier.
> no need for more dependencies, run sequelize with yarn exec

- src/app/components/App.scss
- src/app/components/elements/HorizontalMenu.scss
- src/app/components/modules/Header.jsx
- src/app/components/modules/Header.scss
- src/app/components/modules/TopRightMenu.scss
- src/app/locales/en.json
- src/app/locales/es.json
I made some changes to the primary navigation and removed some elements. As I'm new to the condenser code base, please review to make sure I haven't broken anything. @valzav 
– Increased primary navigation height on large screens (allows for a larger future logo)
– Removal of subnavigation (integrating it with the primary nav)
– Removing titles within the primary nav for people's names and topics 
(future designs will place titles more clearly above the feed on the page)
– Renamed 'Submit a story' to 'Post' inside a button to place more weight on this element.
By removing the dynamic width elements from the navigation, it becomes less fragile and prone to overlapping elements when there are long topics or names.
> Primary navigation

- src/app/components/modules/ConfirmTransactionForm.jsx
- src/app/locales/en.json
- src/app/redux/Transaction.js
- src/app/redux/TransactionSaga.js
This adds an extra layer of protection to users while still allowing you to post a private key if needed (for examples etc.)
I put it at the broadcast level so you will have to confirm any transaction containing keys, should catch all cases, comments/transaction memos/profile description etc.
> Add a confirm to broadcast containing private key wifs

- src/app/components/elements/ReplyEditor.jsx
Before all #hastags found in the post where added to the post category tags preventing you from posting any #hashtag if you've filled out your categories.
After this hashtags found in the post are only added to the categories if they don't exceed the limit of five.
> Update tag parsing logic in reply editor

- src/app/utils/StateFunctions.js
There is logic in condenser that prevents a users post from being hidden if they have reputation > 65. This prevents a high reputation user's posts from being hidden if their account is compromised. This PR removes the high reputation protection, so that any users posts can be hidden if they receive sufficient downvotes.
> Remove reputation protection from downvote post hide

- src/app/components/cards/PostSummary.jsx
#1956 There were a few instances of the old `<a>` tags left that launched modals. This removes them.
> 1956 kill that darned modal

- package.json
- src/app/components/cards/Comment.jsx
- src/app/components/pages/Post.jsx
- src/app/utils/UserUtil.js
- src/shared/UniversalRender.jsx
- yarn.lock
Closes #1946 
Page scrolling on hash navigation and on 'cold landing' has been, spread across multiple files, difficult to maintain and not meeting user expectations.
This pr moves all scrolling behavior into UniversalRender, within a class dedicated to the purpose.
Header-height is determined in one location, and scrolling is done by a scrolling middleware that's called at the correct times by Router, rather than ad-hock native access as was previously done in Comment and Post .jsx files.
Elimination of some ui-jumping in the post page was a part of this process.
> centralize & standardize hash link scroll behavior

- src/app/components/App.jsx
Currently the "Steemit API Links" URL is pointing to `https://steemit.github.io/steemit-docs/`. Update it to point to the new Dev Portal: `https://developers.steem.io/`
> Update Steemit API Links URL

- webpack/base.config.js
fixes runtime error introduced in #1988 
error occurs in server- and client-side
> change ref from old steemjs lib to new one

- package.json
- yarn.lock
This reverts commit a6f8bb321457eb8cb0e4f02e4d7c5e726e0c944c, reversing
changes made to f278085b618d2255308db50c4c191aaf1a855507.
this merge causes build failures because `blueimp-file-upload` is still required in `webpack/base.config.js`
master is currently broken
> Revert "Merge pull request #2113 from steemit/remove-unused-dep"

- src/app/components/elements/ReplyEditor.jsx
Users want the ability to be able to power up 100% on comments. Maybe they will also want to decline payout.
Enable the comment payout editor on comments as well as posts.
- declined payout
- 100% power up comment
- 0% payout comment
> Show payout options on comments

- package.json
- src/app/components/all.scss
- src/app/components/modules/Transfer.jsx
- src/app/components/modules/Transfer.scss
- src/app/locales/en.json
- webpack/dev.config.js
- webpack/prod.config.js
- yarn.lock
Due to the inability to turn on basic autocomplete in the transfer form, users were encountering issues and scams by sending transfers to users with the wrong name. This is largely due to the fact that users had to constantly retype the name of the users they were sending transfers to.
As a solution to this issue, I have enabled the ability for condenser to check the users transfer history and suggest accounts based off this information.
This implementation of the autosuggest transfer feature activates only when the first letter of the name is typed and matched with available results. On top of this, the results are limited to 10 matches at a time in an effort to reduce screen disruption.
> Enable auto suggestion for transfer input based off of users own transfer history

- src/app/components/modules/Transfer.jsx
closes #2189
when i set up the autocomplete widget i didn't notice some loose couplings between the previous input element & our ReactForm system.
> mark "to" field as touched after it is changed

- src/shared/HtmlReady.js
- src/shared/HtmlReady.test.js
closes #2178
see https://github.com/steemit/condenser/pull/2192 for discussion
DO NOT MERGE until we (especially @roadscape) take a long hard look!
i did quite a bit of testing and auditing and didn't see any circumstances where we give htmlready known-to-crash-xmldom strings & are expecting the raw html to be returned. if we deploy this PR it should be in tandem with #2152 so we can track any errors if they happen.
> change htmlready to throw error if xmldom throws an error

- src/shared/HtmlReady.js
- src/shared/HtmlReady.test.js
closes #2226
this broadens the matching pattern of the original phishy link detector from #1839
> match phishy links even without a protocol

- src/app/components/cards/MarkdownViewer.jsx
closes #2246 
i'm not really sure why all these assumptions are made in [MarkdownViewer](https://github.com/steemit/condenser/blob/dcdad264d8cbf39e6c3d5344b26fadfe82169b50/src/app/components/cards/MarkdownViewer.jsx#L72-L80).
this is a hack; it will get us by until we get a chance to overhaul this html sanitizing/rendering pipeline.
> wrap a root-level iframe in html tags to avoid xmldom error

- src/shared/HtmlReady.js
- src/shared/HtmlReady.test.js
closes #2276
we should log these
> return a message rather than throwing if xmldom cannot parse

- Dockerfile
closes #2352
this ensures that a build will fail if yarn.lock is not in sync with package.json
> during docker build, use our yarn.lock

- src/app/utils/JsPlugins.js
fixes: #2379
Documentation for implemented changes:
GA Tracker create method with fields object:
https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers
GA Tracker create method sample rate field:
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#sampleRate
> set google-analytics sample rate to 5, refs #2379

- src/app/components/cards/PostFull.jsx
- src/app/utils/JsPlugins.js
Closes #1990 
This sharer link on the fb side might stop working someday.
For the record, we'd previously delayed loading of the fb sdk but that made the popup get blocked more frequently (https://github.com/steemit/condenser/pull/1151).
> Use a regular popup & share link rather than fb-sdk for facebook sharing

- package.json
closes #2167
you can test this change by doing
```
git co 65782dc2044d0a7cbf3fa36d6739e602ba678942
```
(this is the commit that caused problems before in #2113)
applying the change:
```diff
diff --git a/package.json b/package.json
index 706d8cf..6f2866b 100644
--- a/package.json
+++ b/package.json
@@ -8,7 +8,7 @@
"description": "steemit.com is the koa web server & middleware and react.js in-browser code for the world's first blockchain content + social media monetization platform!",
"main": "index.js",
"scripts": {
-    "build": "NODE_ENV=production webpack --config ./webpack/prod.config.js; rm -rf ./lib; babel src --out-dir lib -Dq",
+    "build": "NODE_ENV=production webpack --config ./webpack/prod.config.js && rm -rf ./lib && babel src --out-dir lib -Dq",
"mocha": "NODE_ENV=test mocha …
```
> pass up an error if something goes wrong during build

- src/app/assets/stylesheets/foundation-overrides.scss
- src/app/components/cards/PostSummary.jsx
- src/app/components/pages/PostsIndex.scss
> add placeholder for loading images in blogmode, refs #2459

- src/app/utils/ChainValidation.js
- src/app/utils/ReactForm.js
closes #2387 
re-closes #2282 
reverts the debounced setState which caused user frustration (#2387)
i came up with a different way of solving #2282 -- instead of testing if every word in the memo field might be a private key, it only runs the expensive "is this a private key" tests if the word is at least the size of a what private key would be.
> fix form validate debounce regression

- src/server/api/general.js
closes #2509
nginx will still apply a higher rate limit so we are still protected.
also a request will get denied quickly if it doesn't supply the correct secret.
i moved the secret check above the logger line so that we can't get logspammed.
> remove rate limit from create_user endpoint

- .nsprc
- package.json
- yarn.lock
closes #2527
none of our dependencies which depend on hoek have updated to fix this issue
luckily the issue is not relevant to any of our runtime code -- the vulnerable version of hoek is used by babel-cli, node-sass, sqlite3, and webpack -- none of these are runtime deps
(well webpack is sorta runtime but its usage of hoek is only during dev usage (watchpack))
also this PR removes grant-koa -- its usage was removed in 135578eaa8216e5843f0b107f1ab0117bf6183eb
> ignore hoek vulnerability

- src/app/components/cards/TransferHistoryRow.jsx
- src/app/components/cards/TransferHistoryRow.scss
- src/app/components/elements/Memo/Memo.test.jsx
- src/app/components/elements/Memo/index.jsx
- src/app/locales/en.json
- src/app/redux/FetchDataSaga.js
- src/app/redux/GlobalReducer.js
- src/app/redux/GlobalReducer.test.js
closes #2397
closes #2306 
when loading the transfers route, fetch accounts involved in `from` transfers so their reputation can be considered, as well as fetch the user account again so their reputation can be reflected in the header.
also improve the logic in Memo/TransactionHistoryRow a bit, and lighten the caution message red color a little for improved contrast.
> Fetch accounts involved in transfers & clickwall their memos

- src/app/components/elements/Memo/index.jsx
closes #2596
We have decreased the threshold (down to 15 from what was effectively 25.0000001) for the bad-rep memo in the transfer history.
> hide memos in transfers from users with negative rep, but not 25

- src/app/Main.js
- src/app/utils/FrontendLogger.js
- src/app/utils/FrontendLogger.test.js
- webpack/prod.config.js
closes #2222
related to #2152 
to test this, you need to do a production build -- it will not work when webpack does a development (sourcemaps included) build.
@jnordberg it looks like overseer is OK with an arbitrary object shape being passed as `metadata`, right? https://github.com/steemit/overseer/blob/master/src/server.ts#L61-L64
it'd probably be wise to decide on a format for these logs -- we can look at sentry for inspiration maybe
> log stack traces if available

- src/app/components/cards/PostSummary.jsx
Resolves #2580
Currently, clicking a child comment on users comments/replies tabs will take you to the OP with the specific comment highlighted. This does not work well when there are a lot of comments.
The new behavior is to link to the direct parent, making the relevant comment much easier to spot. (It's still highlighted). Also, the comments count/icon links directly to the comment, but jumps to the comments section.
> in post lists, link comments/replies to parent, not root

- src/shared/HtmlReady.js
- src/shared/HtmlReady.test.js
Resolves #2556 (plus another found bug which is the 2nd added test case)
Paste the valid comment URL `https://steemit.com/spam/@test-safari/34gfex-december-spam#@test-safari/re-test-safari-34gfex-december-spam-20180110t234627522z` into https://steemit.com/submit.html and see that the resulting URL is munged and the username within it is linked
Paste `valid mention match but invalid username..@usernamewaytoolong` into https://steemit.com/submit.html and see that one of the period is missing even though the username did not get linked.
> fix mentions embedded within naked comment urls

- src/app/redux/AuthSaga.js
Fixes #2593  assuming it has to do with a role-suffix on the user name when doing the login flow.
Description of Problem:
When using eonwarped/active and corresponding password to login while performing a transaction operation such as powering up or transfering funds, or in the case of the referenced issue, changing the account profile, you would get an error like this:
The reason was because of the suffix role, and it simply needs to be stripped. That's what's in this pull request.
> Community - Fix "Account not found" but when using usernames with role suffixes

- src/app/components/modules/Settings.jsx
- src/app/locales/en.json
- JP was added in #2675 but had no switch
- fix awkward missing punctuation:
> fix EN grammar, add JP switch

- src/app/components/cards/Comment.jsx
react-dom/server does not do well with a lot of dom nodes, and this is a dirty way to make SSR quite a bit faster.
on master:
```
Running 15s test @ http://localhost:8080/blackpanther/@cinemax/black-panther-black-panther-full-movie-2018-free-hdrip-dvdrip-bluray-download
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     0.00us    0.00us   0.00us    -nan%
Req/Sec     0.00      0.00     0.00    100.00%
9 requests in 15.02s, 18.81MB read
Socket errors: connect 0, read 0, write 0, timeout 9
Requests/sec:      0.60
Transfer/sec:      1.25MB
```
cutoff at 100 newlines:
```
Running 15s test @ http://localhost:8080/blackpanther/@cinemax/black-panther-black-panther-full-movie-2018-free-hdrip-dvdrip-bluray-download
2 threads and 10 connections
Thread Stats …
```
> Don't SSR a comment if it has more than 10 newlines

- src/app/components/modules/ExplorePost.jsx
phist.steemdata.com was discontinued together with the SteemData.com MongoDB instance on May 1st 2018:
https://steemit.com/steemdata/@furion/steemdata-is-shutting-down-on-may-1st
> ExplorePost: remove steemdata.com from options

- src/app/components/cards/PostSummary.jsx
> The page loads on long posts or posts with many replies are a unneeded, and the `#` scrolling on pageload from the URL is unreliable.
> link directly to comment, not its parent

- package.json
- src/app/Main.js
- src/server/app_render.jsx
- src/server/requesttimings.js
- src/server/server.js
- src/server/utils/RequestTimer.js
- src/server/utils/StatsLoggerClient.js
- src/shared/UniversalRender.jsx
- yarn.lock
closes steemit/steempunks#333
doing a "loading" page is not desirable or advantageous right now, it turns out. instead, this is a refactor of the react render code as well as the addition of request timing logging using statsd (ends up in scalyr).
see logs like this: https://www.scalyr.com/events?filter=path4%3D%22request%22&mode=graph&teamToken=KBolCc6pavrJcaaz%2F4zDPw--&breakdownFacet=path5&logSource=*dev-statlyr*&startTime=1527254075447&facet=value&endTime=1527254214813
> add request metrics to server-side render, and refactor

- src/app/components/pages/Witnesses.jsx
- src/app/locales/en.json
Replaces PR #2228 by @netuoso:
> ### Issue
> There is no distinction between a disabled and active witness on the witness page.
> 
> ### Solution
> Add a logic check and change the CSS for the name of the witness.
> 
> ### Summary
> If there are disabled witnesses in the top 50, users are unaware because the Condenser witness page does not show any distinction. This pull request contains code that will perform a basic check on the witness price feed and signing key. If the price feed is blank or the signing key is the disabled key, the witness name will be grey and strikethrough.
> 
> ### Screenshots
> - Without CSS
> ![screen shot 2017-12-26 at 11 08 24 pm](https://user-images.githubusercontent.com/7006965/34371312-b2c15b5c-ea91-11e7-976b-5454e5109afc.png)
> - With CSS
> ![screen shot …
> distinguish disabled witnesses

- src/server/app_render.jsx
- src/server/server.js
- src/server/utils/misc.js
closes https://github.com/steemit/steempunks/issues/332
With the changes in this PR and following profiling commands
I am seeing:
```
232.76 kb/s avg before.
253.1 kb/s avg after.
8.73 % increase in kb/s.
685.3 req/100s before
899 req/100s after
31.24% increase in requests/s
```
Per:
https://gist.github.com/gl2748/5ee5b145ef2f168895cce74a3466f321
This on the parent process as reported by:
```
yarn run build && SDC_DATABASE_URL="mysql://root@localhost/steemit_dev" NODE_ENV=production node --prof --log_timer_events lib/server/index.js
```
So not too bad. I have a hunch that fs reads for translations might also be slowing things down server side.
> reduce server-side fs reads, refs #332

- src/app/redux/TransactionReducer.js
Local branch for #2858 by @eonwarped:
> #2847 Voting weight too small fix.
> 
> ![errorpic](https://user-images.githubusercontent.com/34953718/41198194-736b49ea-6c41-11e8-87e5-5e9d9d42e1a4.PNG)
> 
> Very quick fix to change error message.
> voting weight error clarification

- Dockerfile
- config/custom-environment-variables.json
- config/default.json
- src/server/server.js
Because these variables exist statically within the image and are set at build time, we don't want to set them as part of the config object. This makes data from `/.well-known/healthcheck.json` useful.
> Fix docker build arg env vars

- src/app/components/modules/UserWallet.jsx
- src/app/locales/en.json
Local PR for @Smittyvb's #2973:
> Adds ![Transactions will not show until they are confirmed on the blockchain, which may take a few minutes.](https://vgy.me/PiZnw6.png)
> Uses i18n key ``transfer_jsx.transactions_make_take_a_few_minutes``.
> Closes #2900.
> Community - Add message warning that transactions could be delayed (#2900)

- src/app/components/modules/Header/index.jsx
- src/app/components/modules/Modals.jsx
This disables the information banner but leaves it intact for future use. It also removes additional unnecessary modal text.
> Disable information banner and remove extra modal text

- src/app/utils/ProxifyUrl.js
- src/app/utils/ProxifyUrl.test.js
Caps blog post image size and should finish the work to dramatically reduce bandwidth costs.
The work has been deployed `imageproxy` side, so we cap images by default, but clients can override the default if they need higher res. However, any blog post image on `condenser` will still be cached at the uncapped size, so this branch makes sure that the URLs are formatted such that they're rendered and cached at the capped size.
This change is easily reversible in case we wish to roll back this behavior later, by simply reverting the commit and re-deploying `condenser`.
> Cap image size to save on bandwidth costs

- src/app/components/modules/UserWallet.jsx
Fixes a bug where going from user's Blog -> Wallet causes errors which break further navigation. Solution is to skip rendering until full acct data is loaded.
> prevent wallet render if acct is lite

- src/server/index.js
Condenser is not using the config object / env var for the server side steemd URL, it is using the client URL in both places. This resolves that.
> Make server side use the server side steemd url

- .circleci/config.yml
Until we have time to update the black box tests, this is a nice simple piece of housekeeping for visual sanity on github.
> Disable blackboxtest workflows for now

- src/app/components/elements/GptAd.jsx
From @economicstudio #3202:
> Close #3201 
> 
> Currently, 404 not found page is as follows:
> ![](https://user-images.githubusercontent.com/38183982/52164375-4990b800-26e8-11e9-9a5e-6d662a2d71b6.png)
> 
> Show "steemitbeta" as a text looks too beta :)
> 
> What about this?
> 
> ![](https://user-images.githubusercontent.com/38183982/52164380-675e1d00-26e8-11e9-84c5-2e698f47d5dc.png)
> 
> This is also good for consistency with normal pages.
> Community - Show Steemit logo instead of text on 404 not found

- src/app/redux/TransactionSaga.js
From @eonwarped #3292:
> In the permlink creation code, restore substitution code at the end as well, as account name can also have invalid permlink characters.
> 
> Should resolve #3291
> 
> Untested, but will verify shortly.
> Community - Fix comment error for authors with special characters

- src/app/components/cards/PostsList.jsx
This simply removes the pin icon on the pinned posts feature, and changes the wording to say 'Featured'.
Things this doesn't do: renaming 'pinned posts' in the code elsewhere, it is only a quick visual change for now.
>  Remove pin icon, rename pinned to featured

- src/server/json/post_json.jsx
- src/server/json/user_json.jsx
From @netuoso #3156:
> Closes #3155 
> 
> This PR intercepts requests made for users in the GDPRUserList.jsx blocklist and responds to requests with a 451 status code instead of a 404 status code.
> 
> These changes result in a prevention of any aspect of the page load process. Changes were also made to the PostJson and UserJson parser to prevent returning data for blocked users.
> 
> This implementation is live on https://mspsteem.com/ and can be tested by visiting the following links:
> `https://mspsteem.com/@thedarkoverlord`
> `https://mspsteem.com/thedarkoverlord/@thedarkoverlord/thedarkoverlord-is-now-on-steemit`
> Community - Return '451 Content unavailable' for users on black lists

- src/app/components/elements/ReplyEditor.scss
From @quochuy #3309:
> Setting the max-width of editor preview to 42.125rem so that it renders to exactly 640px like the post width
> 
> ![Screen Shot 2019-05-03 at 7 35 43 pm](https://user-images.githubusercontent.com/310654/57129926-49818080-6ddb-11e9-9c44-8f28899d6743.jpg)
>
> Community: Set editor preview max-width to 42.125rem

- package.json
- yarn.lock
This version of steem-js includes the fix to use `get_block_header` instead of `get_block` to gather the pervious block id when preparing a transaction (data transfer usage / performance savings for client and server).
> Bump steem-js version to 0.7.5

- src/server/server.js
It has been requested that ads.txt load in a browser instead of prompt a download automatically. Since you can't set `Content-Type` using `koa-static-cache`, this PR loads the file in at startup and serves using only `koa-mount` and setting the content type.
> Serve ads.txt without staticCache

- src/app/components/App.scss
- src/app/components/cards/Comment.jsx
- src/app/components/cards/Comment.scss
- remove depth indicators as not needed now that comments layers are clearly defined
- new comment classes .downvoted and .revealed to have more precise CSS selectors
- hide the voting block from comments when collapsed as the block is too narrow, it breaks the layout. It does not make sense to vote/downvote without reading a comment anyway.
- tweaked and added more precise CSS selectors (for precedence) to fix the border issues with children comments of downvoted comments
> Fix border issues with comments

- src/app/components/cards/Comment.jsx
- src/app/components/cards/PostFull.jsx
From @quochuy #3369:
> Fixes #3362 - Only show reply link to logged in users under posts and comments
> Community - Only show reply link to logged in users

- src/app/components/elements/GptAd.jsx
The ID of the element and the ID of the "slot" needs to be unique to each unit on the page. The in-feed units use the same ID because I was using the ad unit ID, which is generated by the ad manager. Since none of the in-feed ads render at the same time, this is a simple way to make the slot IDs a little unique -- unique enough.
> Make Slot Id Slightly More Unique

- src/app/locales/en.json
From @quochuy #3432:
> Closes #3290: Make modal text for viewing posting key clearer
> Community - clarify modal text for viewing posting key

- src/app/components/cards/Comment.jsx
Certain posts are currently failing to load and return the infamous Steemit 'robot error page'. This is caused by a bug introduced in #3456 and is resolved with this PR.
Example posts:
https://steemit.com/curation/@transisto/steemium-likwid-quick-easy-money-if-you-don-t-take-it-someone-else-will
https://steemit.com/blocktrades/@blocktrades/blocktrades-rocksdb-proposal-to-steemit
> Fix bug introduced in state cleanup project that causes 'missing posts'

- src/app/utils/steemApi.js
From @quochuy #3482:
> Fixes #3481
>
> This bug would have affected all posts that have a title starting with "Curation Rewards" or "Author Rewards"
> Community - Fix 'transfer' page aliases

- src/app/components/pages/Post.jsx
From @quochuy #3483:
> Closes #3480 - Don't two ads in the comments when there are less than 5
> Community - hide ad when less than 5 comments

- src/app/components/cards/PostFull.jsx
- src/app/locales/en.json
- src/app/redux/GlobalReducer.js
Allows a moderator/admin to pin and unpin a post within a community.
- The post doesn't seem to update after a successful change to the post's pin/unpinned status.
- Logic to gate on whether the user is a moderator/admin needed.
Closes #3463
> Add Ability to Pin/Unpin a Community Post

- src/app/components/cards/Comment.jsx
- src/app/components/cards/PostFull.jsx
- src/app/components/elements/MuteButton.jsx
- src/app/components/elements/MuteButtonContainer.jsx
- src/app/components/modules/MutePost.jsx
- src/app/locales/en.json
This allows a user to mute a post, provide a note regarding the mutage, and
unmute a previously muted post.
Screenshots:
Issues:
- ~~The user is not prompted for notes when unmuting.~~
- The layout of the dialog needs love.
- Comments don't full refresh after being muted therefore the user muting the comment will not see the comment greyed out until the page reloads.
Closes #3501
> Add ability to mute a post

- src/app/components/elements/SettingsEditButton.jsx
- src/app/components/elements/SettingsEditButtonContainer.jsx
- src/app/components/modules/CommunitySettings.jsx
- src/app/components/pages/PostsIndex.jsx
- src/app/locales/en.json
> Add Community Settings Editor

- src/app/components/modules/SidePanel/index.jsx
- src/app/locales/en.json
From @imwatsi #3554:
> This adds "Steem Proposals" link in the hamburger menu. Issue #3530 .
> 
> Translations in /src/app/locales will need new key:value pairs for `steem_proposals`.
> Community - add proposals to hamburger menu

- src/app/components/elements/GptAd.jsx
- src/server/server-html.jsx
There was an occasional condition where `enabled` within `GptAd` and `enabled` passed in through props were not the same - this was caused when the google ad script was not loaded prior to beginning to render ads. Since BSA's optimize script already handles this, we don't need to check for it here.
Fixing this problem uncovered an additional one - occasionally BSA's optimize queue would not exist prior to trying to push items to it. Pre-initializing an empty queue solves this.
> Fix occasionally disabled ads issue

- src/app/components/modules/PostAdvancedSettings.jsx
From @eonwarped #3632
> Remove clause that likely never worked. Tested locally to make sure input errors are shown properly as before.
> Community - Fix minor error on beneficiary setting error case

- config/custom-environment-variables.json
- config/default.json
- src/app/assets/ads.txt
- src/app/components/all.scss
- src/app/components/cards/PostsList.jsx
- src/app/components/elements/VideoAd.jsx
- src/app/components/elements/VideoAd.scss
- src/server/app_render.jsx
- src/server/server-html.jsx
This adds a video ad after the 5th post in a post list when turned on via environment variable `VIDEO_ADS_ENABLED`. It adds *.streamrail.com as a default source for media streaming. I added this because we just use the default for media sources and do not set them via environment variable as they don't change very often.
These three hosts are required to be added to the `connect-src` CSP directives, but can be added via environment variable: `sdk.streamrail.com api.vidiom.net *.streamrail.net`.
> Streamrail Video AD through BSA's optimize

- src/app/components/pages/CommunitiesIndex.jsx
- src/app/components/pages/CommunitiesIndex.scss
- src/app/components/pages/PostsIndex.scss
- allow community content to take all available width
- align the top of each column
Desktop:
Mobile:
Tablet:
> Make design consistent with post index

- src/app/components/elements/Follow/index.jsx
- Show "Follow" button from server side rendering
- If user is logged on, the frontend will hide the "Follow" button until it gets a definitive result from API.
> Only show Follow button in user profile banner when we are sure.

- src/app/components/cards/NotificationsList.jsx
- src/app/components/modules/Header/index.jsx
- src/app/components/modules/Header/styles.scss
- src/app/redux/FetchDataSaga.js
Closes #3665 was being caused by:
1. Front-end marks notifications as read.
2. Hivemind responds that mark-as-read action was successful.
3. Front-end immediately makes a request for all 'unread notifications'.
4. Hivemind responds with the previously unread notifications count because the action in 2. has not propagated to the db-layer/blockchain yet.
5. User thinks the unread notifications count is wrong and instead refreshes the browser, (F5).
This PR adds a *10s* delay between 2 and 3.
> 3665 bugfix notifications mark as read

- src/app/components/cards/PostSummary.jsx
- src/app/components/cards/PostsList.scss
> 3685 relocate pinned post badge

- src/app/components/modules/Header/index.jsx
> 3709 login signup css

- src/app/components/modules/Header/index.jsx
> header spacing, fixes #3729

- src/app/components/cards/Comment.jsx
@gl2748 here is the fix for the side-by-side editor
Bug: when replying to a comment, it's showing side-by-side while it should be one above the other for comment editing.
> Fix reply editor when replying to a comment

- src/app/components/elements/PdfDownload.jsx
1. add tron account on pdf file
usage:
need to pass extra two props :
tron_address:  tron account address
tron_key:          tron private key 
ex:
//   <PdfDownload
name={username.value}
password={password.value}
tron_address= {xxxx}
tron_key = {xxxxx}
widthInches={8.5}
heightInches={11.0}
label="Click Download"
//   />
> add tron account into pdf file

- src/app/components/cards/PostsList.jsx
- src/app/components/cards/PostsList.scss
- src/app/components/elements/CommunityBanner.jsx
- src/app/components/elements/CommunityBanner.scss
- src/app/components/pages/PostsIndex.scss
- src/app/locales/es.json
- src/app/locales/fr.json
- src/app/locales/it.json
- src/app/locales/ja.json
- src/app/locales/ko.json
- src/app/locales/pl.json
- src/app/locales/ru.json
These changes add "Hide Resteems" functionality to all Friends Feeds and improves the layout of the Community Banner on mobile devices (when there are a large number of subscribers or rewards).
@ety001 - Could you deploy to steemitdev please?
> #proposal 86 hide resteems

- src/app/components/cards/PostFull.jsx
Fix for bug #3937 
If there's no community information in the state, call the geCommunity function to update the state.
This information is then used to update the page permissions for admins and moderators.
@ety001 - Please can you deploy to steemitdev.com
> Fixed Bug #3937

- README.md
- src/app/components/modules/Settings.jsx
- src/app/components/modules/Settings.scss
This PR replaces the select dropdown for selecting the Steem RPC node with an input and datalist tags improving the user experience by allowing searchable suggestions and free-text input.
- Enhanced UX: Users can now type directly into the input field to quickly find RPC nodes, especially useful if the list grows.
- Flexibility: Allows advanced users to input custom RPC endpoints if needed.
- Modernization: Provides a cleaner, more responsive UI, resembling an auto-complete experience.
- Replaced the select element with an input + datalist in the Settings component.
- Updated Settings.scss to style the new input field for consistency with the existing UI.
- Verified that the new input shows all RPC nodes as suggestions.
Before:
After: (especially that users can add their own node which is …
> Use datalist to show the nodes

- src/app/components/cards/PostFull.jsx
When a post isn't in a community, an "undefined" category is sent to GetCommunity which causes an error.
> Voting Bug Fix

- src/app/components/modules/Settings.jsx
#3949 
Tested locally. Updating "About" works fine.
> Change "about" from textbox to textarea
